import { StyleSheet } from 'react-native';
import { BoardTheme } from './board-theme';

export function createBoardStyles(
  theme: BoardTheme,
  textScale = 1,
  boardSize = 366,
  ordinaryNotes = false,
) {
  const { colors: palette, marks } = theme;
  const candidateSlotSize = boardSize / 27;
  const candidateFontSize = Math.max(
    9.5,
    Math.min(12 * textScale, candidateSlotSize - 2.5),
  );
  const candidateLineHeight = Math.min(
    candidateFontSize + 1.2,
    candidateSlotSize - 0.5,
  );

  return StyleSheet.create({
    boardContainer: { alignSelf: 'center' },
    fishFinSwatch: { backgroundColor: palette.fishFin },
    diagramFin: {
      borderWidth: 2,
      borderColor: palette.fishFin,
      backgroundColor: palette.fishFinSoft,
    },
    diagramFinDigit: { color: palette.fishFin },
    fishBaseSwatch: {
      backgroundColor: palette.fishBaseSoft,
      borderColor: palette.fishBase,
      borderWidth: 1,
    },
    fishCoverSwatch: {
      backgroundColor: palette.fishCoverSoft,
      borderColor: palette.fishCover,
      borderWidth: 1,
    },
    fishLegend: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      paddingTop: 10,
      paddingBottom: 2,
    },
    fishLegendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexShrink: 1,
    },
    fishLegendSwatch: { width: 16, height: 12 },
    fishLegendText: {
      color: palette.ink,
      fontSize: 12 * textScale,
      flexShrink: 1,
    },
    colorLegendSwatch: { width: 16, height: 16 },
    colorLegendConflict: {
      borderColor: palette.error,
      borderWidth: 2,
    },
    board: {
      alignSelf: 'center',
      overflow: 'visible',
      position: 'relative',
    },
    cell: {
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
    },
    cellTeachingLayer: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 1,
    },
    cellContentLayer: {
      alignItems: 'center',
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 2,
    },
    feedbackCell: {
      alignItems: 'center',
      bottom: 0,
      borderWidth: 2,
      justifyContent: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 5,
    },
    feedbackBoard: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      borderWidth: 3,
    },
    cellInteractionLayer: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 6,
    },
    selection: {
      position: 'absolute',
      inset: 2,
      borderWidth: marks.selectionWidth,
      borderColor: palette.focus,
      zIndex: 6,
    },
    cellRoleFill: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    value: {
      fontSize: 28 * textScale,
      fontVariant: ['tabular-nums'],
      lineHeight: 33 * textScale,
    },
    given: {
      color: palette.ink,
      fontWeight: '800',
    },
    player: {
      color: palette.accent,
      fontWeight: '600',
    },
    oneTapDigit: {
      color: palette.hintCandidate,
      fontSize: 24 * textScale,
      fontWeight: '900',
    },
    error: {
      color: palette.error,
      textDecorationLine: 'underline',
    },
    valueEvidence: {
      color: palette.hintCandidate,
      fontWeight: '900',
    },
    valueEvidenceRing: {
      borderColor: palette.hintCandidate,
      borderRadius: 999,
      borderWidth: 2,
      height: 37 * textScale,
      position: 'absolute',
      width: 37 * textScale,
    },
    valueFocusContext: {
      color: palette.focus,
      fontWeight: '800',
    },
    unfocusedCandidate: { opacity: 0.35 },
    inactiveTeachingColor: { opacity: 0.24 },
    hidden: { opacity: 0 },
    teachingColorFrame: {
      position: 'absolute',
      top: 5,
      right: 5,
      bottom: 5,
      left: 5,
    },
    teachingColorCircle: { borderRadius: 999 },
    teachingColorSquare: { borderRadius: 0 },
    teachingGroupFrame: {
      position: 'absolute',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: palette.hintCandidate,
    },
    teachingGroupLabel: {
      fontSize: 9,
      color: palette.ink,
      backgroundColor: palette.surface,
      alignSelf: 'flex-end',
    },
    candidateGrid: {
      height: '100%',
      position: 'relative',
      width: '100%',
    },
    candidateSlot: {
      alignItems: 'center',
      height: '33.333333%',
      justifyContent: 'center',
      position: 'absolute',
      width: '33.333333%',
    },
    candidateAttentionSlot: {
      backgroundColor: palette.candidateAttentionBackground,
      borderRadius: marks.candidateRadius,
    },
    candidateRevealBase: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
    },
    candidateBadge: {
      alignItems: 'center',
      borderRadius: marks.candidateRadius,
      height: '90%',
      justifyContent: 'center',
      position: 'relative',
      width: '90%',
    },
    reasoningCandidateRing: {
      backgroundColor: 'transparent',
      borderRadius: candidateSlotSize / 2,
      borderWidth: marks.reasoningCandidateWidth,
      height: '94%',
      left: '3%',
      position: 'absolute',
      top: '3%',
      width: '94%',
    },
    reasoningAssumptionRing: {
      borderStyle: 'dashed',
    },
    reasoningCandidateStrike: {
      borderRadius: 1,
      height: marks.strikeWidth,
      left: '-8%',
      position: 'absolute',
      top: '46%',
      width: '116%',
    },
    reasoningCandidateStrikeAWithB: {
      top: '39%',
    },
    reasoningCandidateStrikeBWithA: {
      top: '54%',
    },
    reasoningSharedEliminationBadge: {
      backgroundColor: palette.reasoningSharedEliminationSoft,
      borderColor: palette.reasoningSharedElimination,
      borderRadius: marks.candidateRadius,
      borderWidth: 1,
      height: '96%',
      left: '2%',
      position: 'absolute',
      top: '2%',
      width: '96%',
    },
    reasoningContradictionStrike: {
      height: Math.max(2.5, marks.strikeWidth * 1.8),
    },
    uniqueNoteBadge: {
      borderWidth: 1,
      borderColor: palette.focusText,
    },
    candidateDigit: {
      color: ordinaryNotes ? palette.accent : palette.muted,
      fontSize: candidateFontSize,
      fontVariant: ['tabular-nums'],
      lineHeight: candidateLineHeight,
      textAlign: 'center',
    },
    candidateAttentionDigit: {
      color: palette.candidateAttentionText,
      fontWeight: '900',
    },
    reasoningCandidateDigit: {
      fontWeight: '800',
    },
    reasoningSharedEliminationDigit: {
      color: palette.reasoningSharedElimination,
      fontWeight: '900',
    },
    candidateElimination: {
      color: palette.hintExcluded,
      fontWeight: '900',
    },
    eliminationStrike: {
      backgroundColor: palette.hintExcluded,
      borderRadius: 1,
      height: marks.strikeWidth,
      transform: [{ rotate: marks.strikeAngle }],
      left: '-14%',
      position: 'absolute',
      top: '45%',
      width: '128%',
    },
    reasoningConflictFrame: {
      backgroundColor: 'transparent',
      position: 'absolute',
      top: 1,
      right: 1,
      bottom: 1,
      left: 1,
      borderRadius: 4,
      borderWidth: 2,
      borderStyle: 'dashed',
      zIndex: 2,
    },
    reasoningConflictRegionFrame: {
      backgroundColor: 'transparent',
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 2,
    },
    reasoningConflictFill: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    placementResult: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
    },
    placementMark: {
      marginRight: 1,
    },
    placementDigit: {
      color: palette.accent,
      fontSize: 24 * textScale,
      fontWeight: '900',
    },
    linkLayer: { ...StyleSheet.absoluteFill, zIndex: 3 },
    hintLink: { position: 'absolute', height: 2, borderRadius: 1 },
    diagramBox: {
      position: 'absolute',
      borderWidth: 2,
      borderColor: palette.hintCandidate,
      zIndex: 5,
    },
    emptyRectangleHatch: { ...StyleSheet.absoluteFill, overflow: 'hidden' },
    emptyRectangleStripe: {
      position: 'absolute',
      left: '-50%',
      width: '200%',
      height: 1.5,
      backgroundColor: palette.hatch,
      opacity: marks.hatchOpacity,
      transform: [{ rotate: '-45deg' }],
    },
    diagramCandidate: {
      width: '74%',
      height: '74%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    diagramAttention: {
      backgroundColor: palette.candidateAttentionBackground,
      borderRadius: 999,
      height: '62%',
      width: '62%',
    },
    diagramAttentionDigit: { color: palette.candidateAttentionText },
    diagramReasoningCandidate: {
      borderRadius: 999,
      borderWidth: 2,
      position: 'relative',
    },
    diagramReasoningAssumption: {
      borderStyle: 'dashed',
    },
    diagramReasoningDigit: {
      fontWeight: '800',
    },
    diagramReasoningQuestion: {
      fontSize: 11 * textScale,
      fontWeight: '900',
      position: 'absolute',
      right: 5,
      top: 2,
    },
    diagramDigit: {
      fontSize: 20 * textScale,
      color: palette.hintCandidate,
      fontWeight: '600',
    },
    diagramStrike: {
      position: 'absolute',
      width: '90%',
      height: marks.strikeWidth,
      backgroundColor: palette.hintExcluded,
      transform: [{ rotate: marks.strikeAngle }],
    },
    diagramStrikePrior: {
      backgroundColor: palette.muted,
      opacity: marks.contextOpacity,
    },
    kiteBackground: { opacity: marks.contextOpacity },
    hintLinkStructure: { opacity: 0.85 },
    hintLinkActive: { opacity: 0.9 },
    hintLinkTarget: { opacity: 0.3 },
    hintLinkContext: { opacity: 0.55 },
    hintLinkMuted: { opacity: 0.28 },
    stableSpotlight: { opacity: 1 },
    hintQuestion: { borderStyle: 'dashed' },
    hintSelectedQuestion: {
      borderStyle: 'solid',
      borderWidth: 3,
    },
    hintTarget: {
      borderColor: palette.hintCandidate,
      borderRadius: 2,
      borderWidth: 2,
      bottom: 3,
      left: 3,
      position: 'absolute',
      right: 3,
      top: 3,
    },
    spotlightMask: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 2,
    },
    spotlightMaskRun: {
      backgroundColor: palette.hintMask,
      position: 'absolute',
    },
    gridLine: {
      backgroundColor: palette.lineStrong,
      position: 'absolute',
      zIndex: 4,
    },
  });
}
