import {
  albumEnglish,
  albumChinese,
  albumJapanese,
  albumGerman,
} from './growth-album-copy';
export const growthEnglish = {
  ...albumEnglish,
  'growth.moreRecords': 'Show more records ({{count}} remaining)',
  'growth.state.unknown': 'Records need more evidence',
  'growth.activeNotice':
    'The game is still in progress. Its technique replay becomes available after it ends.',
  'growth.title': 'My techniques',
  'growth.footprint': 'Technique footprint',
  'growth.intro':
    'Learning and application records, starting with your first game.',
  'growth.note':
    'Records describe learning and explainable applications, not a mastery assessment.',
  'growth.about': 'About these records',
  'growth.aboutBody':
    'Stored locally. Hints, completed walkthroughs and verified application processes are separate. Possible explanations do not count as applications. Missing history stays unknown. Zero records does not mean inability. Later replay learning uses its actual date. Recalculation never creates a new learning celebration.',
  'growth.recent': 'Recent records',
  'growth.followed': 'Following',
  'growth.all': 'All 39 techniques',
  'growth.follow': 'Follow',
  'growth.unfollow': 'Following · Unfollow',
  'growth.empty': 'Your technique footprint starts with your first game.',
  'growth.followEmpty': 'Follow a technique from its detail page.',
  'growth.state.empty': 'No records yet',
  'growth.state.learning': 'Starting to explore',
  'growth.state.applying': 'Applications accumulating',
  'growth.state.multiple': 'Applications across puzzles',
  'growth.state.possible': 'Explanations to revisit',
  'growth.recentSummary':
    'Last {{count}} completed games · {{learning}} techniques encountered · {{applications}} with application records',
  'growth.learningCount': 'Games with learning contact · {{count}}',
  'growth.applicationCount': 'Application processes · {{count}}',
  'growth.puzzleCount': 'Distinct puzzles with applications · {{count}}',
  'growth.records': 'Records by source game',
  'growth.learning': 'Learning contacts',
  'growth.applications': 'Application records',
  'growth.possible': 'Worth revisiting',
  'growth.filterAll': 'All records',
  'growth.kind.hint_viewed': 'Hint shown at the time',
  'growth.kind.hint_applied': 'Hint applied',
  'growth.kind.walkthrough': 'Walkthrough completed',
  'growth.kind.application': 'Verified application · default explanation',
  'growth.kind.possible': 'Possible program explanation',
  'growth.kind.related_finish': 'Related finish · not another application',
  'growth.kind.unknown': 'Evidence incomplete',
  'growth.unknownDate': 'Activity time was not saved',
  'growth.sourceDate': 'Source game: {{date}}',
  'growth.activityDate': 'Activity: {{date}}',
  'growth.view': 'View this step / process',
  'growth.why': 'Why this record?',
  'growth.reason.learning':
    'A saved learning action. Completion does not prove understanding.',
  'growth.reason.verified_process':
    'The complete observed process passed the attribution policy and verification. Its default explanation is not a claim about your thoughts.',
  'growth.reason.possible_path':
    'An alternative, dependent or incompletely observed process. Not counted as a separate application.',
  'growth.reason.dependent_finish':
    'Earlier effects enabled this finish; it does not add another application.',
  'growth.reason.hint_assisted':
    'Saved hint assistance prevents independent attribution.',
  'growth.reason.missing_evidence':
    'Some source, timing or analysis evidence is unavailable. Nothing has been invented to fill the gap.',
  'growth.reason.ineligible':
    'This record does not meet the attribution policy. It is not a negative assessment of ability.',
  'growth.more': 'Show more games',
  'growth.trend': 'Recent changes',
  'growth.insufficient':
    'Keep accumulating records to compare two windows of 10 completed games.',
  'growth.window':
    '{{label}}: {{count}} application processes · {{puzzles}} puzzles · evidence {{covered}}/{{total}} games',
  'growth.last10': 'Latest 10',
  'growth.previous10': 'Previous 10',
  'growth.missingWindow':
    'Some games have missing or pending evidence. No growth conclusion is drawn.',
  'growth.noApplication': 'No applications recorded in this window.',
  'growth.milestones': 'Learning milestones',
  'growth.milestone.contact': 'Earliest recorded learning contact',
  'growth.milestone.walkthrough': 'First recorded walkthrough completion',
  'growth.milestone.diversity':
    'At least 5 processes across 3 puzzles · accumulation only',
  'growth.coverage.pending': 'Learning facts saved · applications pending',
  'growth.coverage.complete': 'Organized · explanations are not mastery',
  'growth.coverage.incomplete': 'Organized · some evidence remains unknown',
  'growth.coverage.failed': 'Analysis unavailable · retry',
  'growth.retry': 'Retry',
  'growth.updating': 'Updating records in the background…',
  'growth.failed':
    'Records could not be refreshed. Saved entries are retained.',
  'growth.unlocatable':
    'The referenced step cannot be located. You can open the full replay below.',
  'growth.startProcess': 'Process start',
  'growth.endProcess': 'Process finish',
  'growth.walkSaved':
    'This walkthrough was recorded. Completion does not mean understanding.',
  'growth.lightSetting': 'In-game learning feedback',
  'growth.summarySetting': 'Post-game technique summary',
  'growth.settingHint': 'Controls display only; your records stay saved.',
  'growth.light': 'Learning recorded: {{technique}}',
  'growth.emptyFootprint':
    'No technique records yet. The full replay is still available.',
  'growth.levels': 'Difficulty mix: {{levels}}',
} as const;
export const growthChinese = {
  ...albumChinese,
  'growth.moreRecords': '查看更多记录（剩余{{count}}条）',
  'growth.state.unknown': '记录证据待补充',
  'growth.activeNotice': '对局仍在进行。结束后可查看本局技巧复盘。',
  'growth.title': '我的技巧',
  'growth.footprint': '本局技巧足迹',
  'growth.intro': '从第一局开始，记录你的学习与应用。',
  'growth.note': '记录反映学习与可解释的应用，不等于掌握评定。',
  'growth.about': '统计说明',
  'growth.aboutBody':
    '本地保存。提示、完成演练与经过复验的应用过程分别记录；可能解释不计应用。缺失历史保持未知，零记录不代表不会。后来复盘学习按实际日期记录，重算不生成新学习庆祝。',
  'growth.recent': '最近记录',
  'growth.followed': '我关注的',
  'growth.all': '全部39项技巧',
  'growth.follow': '关注',
  'growth.unfollow': '已关注 · 取消关注',
  'growth.empty': '你的技巧足迹会从第一局开始。',
  'growth.followEmpty': '在技巧详情中关注你想继续练习的技巧。',
  'growth.state.empty': '尚无记录',
  'growth.state.learning': '开始接触',
  'growth.state.applying': '应用积累中',
  'growth.state.multiple': '多题有应用记录',
  'growth.state.possible': '有可回看的解释',
  'growth.recentSummary':
    '最近{{count}}局已完成对局 · 接触{{learning}}种技巧 · {{applications}}种有应用记录',
  'growth.learningCount': '学习接触 · {{count}}局',
  'growth.applicationCount': '应用过程 · {{count}}个',
  'growth.puzzleCount': '应用涉及 · {{count}}道不同题目',
  'growth.records': '按源对局查看记录',
  'growth.learning': '学习接触',
  'growth.applications': '应用记录',
  'growth.possible': '值得回看',
  'growth.filterAll': '全部记录',
  'growth.kind.hint_viewed': '当时查看提示',
  'growth.kind.hint_applied': '提示辅助',
  'growth.kind.walkthrough': '完成演练',
  'growth.kind.application': '应用过程 · 系统默认解释',
  'growth.kind.possible': '程序可能解释',
  'growth.kind.related_finish': '相关收尾 · 不另计应用',
  'growth.kind.unknown': '证据不足',
  'growth.unknownDate': '未保存实际活动时间',
  'growth.sourceDate': '源对局：{{date}}',
  'growth.activityDate': '实际活动：{{date}}',
  'growth.view': '查看这一步／过程',
  'growth.why': '为什么这样记录',
  'growth.reason.learning': '已保存真实学习操作，完成不代表理解。',
  'growth.reason.verified_process':
    '完整过程通过统一归因准入与复验。系统默认解释不代表证明了你的真实思路。',
  'growth.reason.possible_path':
    '备选、存在依赖或未完整观察的过程，不计为独立应用。',
  'growth.reason.dependent_finish': '前置效果形成的相关收尾，不再增加应用数。',
  'growth.reason.hint_assisted': '已有提示受助证据，不作独立归因。',
  'growth.reason.missing_evidence':
    '来源、时间或分析证据存在缺失，未补造历史。',
  'growth.reason.ineligible': '本条不满足归因准入，不代表能力较弱。',
  'growth.more': '查看更多对局',
  'growth.trend': '近期变化',
  'growth.insufficient': '继续积累后显示最近10局与之前10局的记录对比。',
  'growth.window':
    '{{label}}：{{count}}个应用过程 · {{puzzles}}道题 · 证据覆盖{{covered}}/{{total}}局',
  'growth.last10': '最近10局',
  'growth.previous10': '之前10局',
  'growth.missingWindow': '部分对局证据缺失或待整理，暂不给增长结论。',
  'growth.noApplication': '该窗口未记录到应用。',
  'growth.milestones': '学习里程碑',
  'growth.milestone.contact': '首次已记录接触',
  'growth.milestone.walkthrough': '首次已记录演练完成',
  'growth.milestone.diversity': '至少3道题、5个过程 · 仅表示事实积累',
  'growth.coverage.pending': '学习事实已保存 · 应用记录待整理',
  'growth.coverage.complete': '整理完成 · 解释不等于掌握',
  'growth.coverage.incomplete': '整理完成 · 仍有未知证据',
  'growth.coverage.failed': '分析暂不可用 · 可重试',
  'growth.retry': '重试',
  'growth.updating': '正在后台整理记录…',
  'growth.failed': '记录更新失败，保留已有内容。',
  'growth.unlocatable': '无法定位所引用的步骤，可在下方打开完整复盘。',
  'growth.startProcess': '过程起点',
  'growth.endProcess': '过程收尾',
  'growth.walkSaved': '本次演练已记录，完成不代表理解。',
  'growth.lightSetting': '对局中轻反馈',
  'growth.summarySetting': '局后技巧摘要',
  'growth.settingHint': '仅控制展示，不删除学习和应用记录。',
  'growth.light': '已记录一次{{technique}}学习',
  'growth.emptyFootprint': '本局暂未形成技巧记录，仍可查看完整复盘。',
  'growth.levels': '难度构成：{{levels}}',
} as const;
export const growthJapanese = {
  ...albumJapanese,
  'growth.moreRecords': 'さらに記録を表示（残り{{count}}件）',
  'growth.state.unknown': '記録の証拠が不足しています',
  'growth.activeNotice':
    '対局中です。終了後にテクニックのリプレイを閲覧できます。',
  'growth.title': '自分のテクニック',
  'growth.footprint': 'この対局の足跡',
  'growth.intro': '最初の対局から、学習と応用を記録します。',
  'growth.note':
    '記録は学習と説明可能な応用を示し、習熟度の判定ではありません。',
  'growth.about': '記録について',
  'growth.aboutBody':
    '端末内に保存。ヒント、完了した演習、検証済みの応用は別々に記録します。可能な説明は応用に加算しません。履歴不足は不明のままです。記録ゼロは能力ゼロではありません。復習は実際の日付を使用します。',
  'growth.recent': '最近の記録',
  'growth.followed': 'フォロー中',
  'growth.all': '全39テクニック',
  'growth.follow': 'フォロー',
  'growth.unfollow': 'フォロー中・解除',
  'growth.empty': '最初の対局から足跡が始まります。',
  'growth.followEmpty': '詳細ページでテクニックをフォローできます。',
  'growth.state.empty': 'まだ記録なし',
  'growth.state.learning': '学習の始まり',
  'growth.state.applying': '応用を蓄積中',
  'growth.state.multiple': '複数の問題で応用',
  'growth.state.possible': '振り返れる説明あり',
  'growth.recentSummary':
    '最近の完了{{count}}対局・学習{{learning}}種・応用記録{{applications}}種',
  'growth.learningCount': '学習との接点・{{count}}対局',
  'growth.applicationCount': '応用プロセス・{{count}}件',
  'growth.puzzleCount': '応用した異なる問題・{{count}}題',
  'growth.records': '元の対局別の記録',
  'growth.learning': '学習との接点',
  'growth.applications': '応用記録',
  'growth.possible': '振り返り',
  'growth.filterAll': 'すべて',
  'growth.kind.hint_viewed': '当時表示したヒント',
  'growth.kind.hint_applied': 'ヒントを適用',
  'growth.kind.walkthrough': '演習を完了',
  'growth.kind.application': '検証済み応用・既定の説明',
  'growth.kind.possible': 'プログラムによる可能な説明',
  'growth.kind.related_finish': '関連する仕上げ・別の応用には加算しません',
  'growth.kind.unknown': '証拠不足',
  'growth.unknownDate': '活動時刻の記録なし',
  'growth.sourceDate': '元の対局：{{date}}',
  'growth.activityDate': '活動：{{date}}',
  'growth.view': '手順・プロセスを見る',
  'growth.why': '記録の理由',
  'growth.reason.learning':
    '保存済みの学習操作です。完了は理解の証明ではありません。',
  'growth.reason.verified_process':
    '観察されたプロセス全体が規則と検証を通過しました。思考内容の断定ではありません。',
  'growth.reason.possible_path':
    '代替・依存・観察不足のプロセスで、独立した応用には数えません。',
  'growth.reason.dependent_finish':
    '前提の効果による仕上げで、応用数には追加しません。',
  'growth.reason.hint_assisted':
    '保存されたヒントの補助があるため独立と判定しません。',
  'growth.reason.missing_evidence':
    '出典・時刻・分析の一部が不足しています。履歴は補作していません。',
  'growth.reason.ineligible':
    '帰属条件を満たしていません。能力の否定ではありません。',
  'growth.more': 'さらに表示',
  'growth.trend': '最近の変化',
  'growth.insufficient':
    '完了した対局が増えると、直近10局とその前10局を比較できます。',
  'growth.window':
    '{{label}}：応用{{count}}件・{{puzzles}}題・証拠{{covered}}/{{total}}局',
  'growth.last10': '直近10局',
  'growth.previous10': 'その前10局',
  'growth.missingWindow': '証拠不足・処理待ちがあるため成長は判定しません。',
  'growth.noApplication': 'この期間の応用記録はありません。',
  'growth.milestones': '学習の節目',
  'growth.milestone.contact': '最初に記録した学習',
  'growth.milestone.walkthrough': '最初に記録した演習完了',
  'growth.milestone.diversity': '3題以上・5プロセス以上・蓄積のみ',
  'growth.coverage.pending': '学習を保存・応用は処理待ち',
  'growth.coverage.complete': '整理完了・説明は習熟の証明ではありません',
  'growth.coverage.incomplete': '整理完了・不明な証拠あり',
  'growth.coverage.failed': '分析できません・再試行',
  'growth.retry': '再試行',
  'growth.updating': '記録を整理中…',
  'growth.failed': '更新できません。保存済みの内容を保持しています。',
  'growth.unlocatable': '参照手順を特定できません。全リプレイを開けます。',
  'growth.startProcess': 'プロセス開始',
  'growth.endProcess': 'プロセス終了',
  'growth.walkSaved': '演習を記録しました。完了は理解を意味しません。',
  'growth.lightSetting': '対局中の学習表示',
  'growth.summarySetting': '対局後の技術まとめ',
  'growth.settingHint': '表示のみを設定し、記録は削除しません。',
  'growth.light': '{{technique}}の学習を記録',
  'growth.emptyFootprint':
    'まだテクニックの記録はありません。全リプレイは閲覧できます。',
  'growth.levels': '難易度構成：{{levels}}',
} as const;
export const growthGerman = {
  ...albumGerman,
  'growth.moreRecords': 'Weitere Einträge ({{count}} verbleibend)',
  'growth.state.unknown': 'Einträge benötigen weitere Belege',
  'growth.activeNotice':
    'Das Spiel läuft noch. Die Technik-Wiedergabe ist nach seinem Ende verfügbar.',
  'growth.title': 'Meine Techniken',
  'growth.footprint': 'Technikspuren',
  'growth.intro': 'Lernen und Anwenden ab dem ersten Spiel festhalten.',
  'growth.note':
    'Die Einträge zeigen Lernen und erklärbare Anwendungen, keine Beherrschung.',
  'growth.about': 'Über diese Einträge',
  'growth.aboutBody':
    'Lokal gespeichert. Hinweise, abgeschlossene Übungen und geprüfte Anwendungen werden getrennt gezählt. Mögliche Erklärungen zählen nicht als Anwendungen. Fehlende Daten bleiben unbekannt. Keine Einträge bedeuten kein Unvermögen. Späteres Lernen erhält das tatsächliche Datum.',
  'growth.recent': 'Letzte Einträge',
  'growth.followed': 'Gefolgte',
  'growth.all': 'Alle 39 Techniken',
  'growth.follow': 'Folgen',
  'growth.unfollow': 'Gefolgt · Entfolgen',
  'growth.empty': 'Deine Technikspuren beginnen mit dem ersten Spiel.',
  'growth.followEmpty': 'Folge einer Technik auf ihrer Detailseite.',
  'growth.state.empty': 'Noch keine Einträge',
  'growth.state.learning': 'Erste Begegnungen',
  'growth.state.applying': 'Anwendungen sammeln sich',
  'growth.state.multiple': 'Anwendungen in mehreren Rätseln',
  'growth.state.possible': 'Erklärungen zum Nachlesen',
  'growth.recentSummary':
    'Letzte {{count}} abgeschlossene Spiele · {{learning}} Techniken kennengelernt · {{applications}} mit Anwendungen',
  'growth.learningCount': 'Lernkontakte · {{count}} Spiele',
  'growth.applicationCount': 'Anwendungsprozesse · {{count}}',
  'growth.puzzleCount': 'Verschiedene Rätsel mit Anwendungen · {{count}}',
  'growth.records': 'Einträge nach Ursprungsspiel',
  'growth.learning': 'Lernkontakte',
  'growth.applications': 'Anwendungen',
  'growth.possible': 'Zum Nachlesen',
  'growth.filterAll': 'Alle Einträge',
  'growth.kind.hint_viewed': 'Damals angezeigter Hinweis',
  'growth.kind.hint_applied': 'Hinweis angewendet',
  'growth.kind.walkthrough': 'Übung abgeschlossen',
  'growth.kind.application': 'Geprüfte Anwendung · Standarderklärung',
  'growth.kind.possible': 'Mögliche Programmerklärung',
  'growth.kind.related_finish':
    'Zugehöriger Abschluss · keine weitere Anwendung',
  'growth.kind.unknown': 'Unvollständige Belege',
  'growth.unknownDate': 'Aktivitätszeit nicht gespeichert',
  'growth.sourceDate': 'Ursprungsspiel: {{date}}',
  'growth.activityDate': 'Aktivität: {{date}}',
  'growth.view': 'Schritt / Prozess ansehen',
  'growth.why': 'Warum dieser Eintrag?',
  'growth.reason.learning':
    'Eine gespeicherte Lernhandlung. Abschluss belegt kein Verständnis.',
  'growth.reason.verified_process':
    'Der beobachtete Gesamtprozess wurde nach den einheitlichen Regeln geprüft. Die Standarderklärung behauptet nichts über deine Gedanken.',
  'growth.reason.possible_path':
    'Ein alternativer, abhängiger oder unvollständig beobachteter Prozess. Keine eigenständige Anwendung.',
  'growth.reason.dependent_finish':
    'Frühere Effekte ermöglichten diesen Abschluss. Keine weitere Anwendung.',
  'growth.reason.hint_assisted':
    'Gespeicherte Hilfestellung verhindert eine unabhängige Zuordnung.',
  'growth.reason.missing_evidence':
    'Quellen-, Zeit- oder Analysebelege fehlen teilweise. Die Lücke wurde nicht erfunden.',
  'growth.reason.ineligible':
    'Dieser Eintrag erfüllt die Zuordnungsregeln nicht. Das ist keine negative Fähigkeitsbewertung.',
  'growth.more': 'Weitere Spiele',
  'growth.trend': 'Letzte Veränderungen',
  'growth.insufficient':
    'Mit weiteren Einträgen lassen sich die letzten 10 abgeschlossenen Spiele mit den 10 davor vergleichen.',
  'growth.window':
    '{{label}}: {{count}} Prozesse · {{puzzles}} Rätsel · Belege {{covered}}/{{total}} Spiele',
  'growth.last10': 'Letzte 10',
  'growth.previous10': 'Vorherige 10',
  'growth.missingWindow':
    'Einigen Spielen fehlen Belege oder Auswertungen. Keine Wachstumsaussage.',
  'growth.noApplication': 'In diesem Zeitraum keine Anwendungen erfasst.',
  'growth.milestones': 'Lernmeilensteine',
  'growth.milestone.contact': 'Frühester erfasster Lernkontakt',
  'growth.milestone.walkthrough': 'Erster erfasster Übungsabschluss',
  'growth.milestone.diversity':
    'Mindestens 5 Prozesse in 3 Rätseln · nur Ansammlung',
  'growth.coverage.pending': 'Lernfakten gespeichert · Anwendungen ausstehend',
  'growth.coverage.complete':
    'Geordnet · Erklärungen bedeuten keine Beherrschung',
  'growth.coverage.incomplete': 'Geordnet · einige Belege bleiben unbekannt',
  'growth.coverage.failed': 'Analyse nicht verfügbar · erneut versuchen',
  'growth.retry': 'Erneut versuchen',
  'growth.updating': 'Einträge werden im Hintergrund aktualisiert…',
  'growth.failed':
    'Aktualisierung fehlgeschlagen. Gespeicherte Einträge bleiben erhalten.',
  'growth.unlocatable':
    'Der referenzierte Schritt lässt sich nicht finden. Die vollständige Wiedergabe ist verfügbar.',
  'growth.startProcess': 'Prozessbeginn',
  'growth.endProcess': 'Prozessende',
  'growth.walkSaved':
    'Diese Übung wurde erfasst. Abschluss bedeutet nicht Verständnis.',
  'growth.lightSetting': 'Lernhinweise im Spiel',
  'growth.summarySetting': 'Technikübersicht nach dem Spiel',
  'growth.settingHint':
    'Steuert nur die Anzeige; Einträge bleiben gespeichert.',
  'growth.light': 'Lernen erfasst: {{technique}}',
  'growth.emptyFootprint':
    'Noch keine Technikeinträge. Die vollständige Wiedergabe ist verfügbar.',
  'growth.levels': 'Schwierigkeitsverteilung: {{levels}}',
} as const;
