export const albumEnglish = {
  'growth.entry.remember': 'A moment to revisit',
  'growth.entry.all': 'See all footprints',
  'growth.entry.recent': 'Recent encounters',
  'growth.entry.empty': 'No technique records yet',
  'growth.entry.start': 'Your games will leave their traces here',
  'growth.entry.pending': 'Organizing this game’s records…',
  'growth.entry.failed': 'Records are unavailable for now',
  'growth.entry.incomplete': 'Some evidence is unavailable',
  'growth.entry.fromGame': 'From this game',
  'growth.entry.count': '{{count}} records',
  'growth.entry.preview': 'Preview this record',
  'growth.entry.previewAbove': 'The preview is at the top of this page',
  'growth.entry.noMatch': 'No records in this category',
  'growth.entry.pendingTitle': 'Records are on their way',
  'growth.entry.pendingBody':
    'Saved learning records appear here while applications are being organized.',
  'growth.entry.emptyBody': 'You can still revisit the full game.',

  'growth.album.subtitle': 'Patterns from your games',
  'growth.album.recent': 'Recent',
  'growth.album.all': 'All 39',
  'growth.album.following': 'Following',
  'growth.album.learning': 'Learning contact',
  'growth.album.application': 'Application recorded',
  'growth.album.possible': 'Possible explanation',
  'growth.album.encounter': 'From your recent game',
  'growth.album.before': 'Before this step · Step {{step}}',
  'growth.album.board':
    'Saved board before step {{step}}. Open replay to inspect the full board and candidates.',
  'growth.album.replay': 'Revisit this step',
  'growth.album.replayProcess': 'Revisit this process',
  'growth.album.history': 'Past encounters',
  'growth.album.numbers': 'Numbers & milestones',
  'growth.album.technique': 'About this technique',
  'growth.album.source': 'Record source',
  'growth.album.noSample': 'Your next encounter belongs here',
  'growth.album.noSampleBody':
    'A step from your own games will appear here when one is recorded.',
  'growth.album.unavailable': 'No saved preview for this record',
  'growth.album.sourceLine': '{{date}} · Level {{level}}',
} as const;
export const albumChinese = {
  'growth.entry.remember': '本局值得回看',
  'growth.entry.all': '查看全部足迹',
  'growth.entry.recent': '最近的技巧经历',
  'growth.entry.empty': '本局暂无技巧记录',
  'growth.entry.start': '从你的下一局开始积累',
  'growth.entry.pending': '正在整理本局记录…',
  'growth.entry.failed': '暂时无法更新记录',
  'growth.entry.incomplete': '部分记录证据不完整',
  'growth.entry.fromGame': '在这局遇见',
  'growth.entry.count': '{{count}}条记录',
  'growth.entry.preview': '预览这条记录',
  'growth.entry.previewAbove': '预览已更新到页面顶部',
  'growth.entry.noMatch': '这一类暂无记录',
  'growth.entry.pendingTitle': '本局足迹正在整理',
  'growth.entry.pendingBody': '已保存的学习记录会先出现，应用记录稍后更新。',
  'growth.entry.emptyBody': '仍可进入完整复盘，回看这局棋。',

  'growth.album.subtitle': '在你的棋盘上，遇见技巧',
  'growth.album.recent': '最近',
  'growth.album.all': '全部39项',
  'growth.album.following': '已关注',
  'growth.album.learning': '学习接触',
  'growth.album.application': '有应用记录',
  'growth.album.possible': '可能解释',
  'growth.album.encounter': '最近在这局遇见',
  'growth.album.before': '操作前 · 第{{step}}步',
  'growth.album.board':
    '第{{step}}步操作前的真实棋盘。进入复盘可查看完整棋盘和候选数。',
  'growth.album.replay': '回看这一步',
  'growth.album.replayProcess': '回看这个过程',
  'growth.album.history': '过往记录',
  'growth.album.numbers': '统计与里程碑',
  'growth.album.technique': '了解这个技巧',
  'growth.album.source': '查看依据',
  'growth.album.noSample': '下一次遇见，就留在这里',
  'growth.album.noSampleBody':
    '当你的对局留下相关记录，这里会出现属于你的那一步。',
  'growth.album.unavailable': '这条记录没有可恢复的预览',
  'growth.album.sourceLine': '{{date}} · Level {{level}}',
} as const;
export const albumJapanese = {
  'growth.entry.remember': 'この対局を振り返る',
  'growth.entry.all': 'すべての記録を見る',
  'growth.entry.recent': '最近の技法との出会い',
  'growth.entry.empty': '技法の記録はまだありません',
  'growth.entry.start': '次の対局から記録を残そう',
  'growth.entry.pending': '対局の記録を整理中…',
  'growth.entry.failed': '記録を更新できません',
  'growth.entry.incomplete': '一部の根拠がありません',
  'growth.entry.fromGame': 'この対局での出会い',
  'growth.entry.count': '{{count}}件の記録',
  'growth.entry.preview': 'この記録をプレビュー',
  'growth.entry.previewAbove': 'ページ上部のプレビューを更新しました',
  'growth.entry.noMatch': 'この種類の記録はありません',
  'growth.entry.pendingTitle': '対局の記録を整理中',
  'growth.entry.pendingBody':
    '保存した学習記録を先に表示し、活用の記録は後で更新します。',
  'growth.entry.emptyBody': '対局全体のリプレイは引き続き見られます。',

  'growth.album.subtitle': '自分の盤面で出会った技法',
  'growth.album.recent': '最近',
  'growth.album.all': '全39技法',
  'growth.album.following': 'フォロー中',
  'growth.album.learning': '学習の記録',
  'growth.album.application': '活用の記録あり',
  'growth.album.possible': '可能な説明',
  'growth.album.encounter': '最近の対局から',
  'growth.album.before': '操作前 · {{step}}手目',
  'growth.album.board':
    '{{step}}手目の直前に保存された盤面。候補を含む全体はリプレイで確認できます。',
  'growth.album.replay': 'この手を振り返る',
  'growth.album.replayProcess': 'この過程を振り返る',
  'growth.album.history': '過去の記録',
  'growth.album.numbers': '統計と節目',
  'growth.album.technique': 'この技法について',
  'growth.album.source': '記録の根拠',
  'growth.album.noSample': '次の出会いをここに',
  'growth.album.noSampleBody':
    '自分の対局で関連する手が記録されると、ここに表示されます。',
  'growth.album.unavailable': 'この記録の盤面プレビューはありません',
  'growth.album.sourceLine': '{{date}} · レベル{{level}}',
} as const;
export const albumGerman = {
  'growth.entry.remember': 'Ein Moment zum Wiederansehen',
  'growth.entry.all': 'Alle Spuren ansehen',
  'growth.entry.recent': 'Letzte Begegnungen',
  'growth.entry.empty': 'Noch keine Technikeinträge',
  'growth.entry.start': 'Dein nächstes Spiel hinterlässt Spuren',
  'growth.entry.pending': 'Einträge werden geordnet…',
  'growth.entry.failed': 'Einträge derzeit nicht verfügbar',
  'growth.entry.incomplete': 'Einige Belege fehlen',
  'growth.entry.fromGame': 'Aus diesem Spiel',
  'growth.entry.count': '{{count}} Einträge',
  'growth.entry.preview': 'Diesen Eintrag ansehen',
  'growth.entry.previewAbove': 'Die Vorschau oben wurde aktualisiert',
  'growth.entry.noMatch': 'Keine Einträge in dieser Kategorie',
  'growth.entry.pendingTitle': 'Spielspuren werden geordnet',
  'growth.entry.pendingBody':
    'Gespeicherte Lernkontakte erscheinen zuerst, Anwendungen folgen später.',
  'growth.entry.emptyBody': 'Du kannst weiterhin das ganze Spiel wiederholen.',

  'growth.album.subtitle': 'Muster aus deinen Spielen',
  'growth.album.recent': 'Zuletzt',
  'growth.album.all': 'Alle 39',
  'growth.album.following': 'Gemerkte',
  'growth.album.learning': 'Lernkontakt',
  'growth.album.application': 'Anwendung erfasst',
  'growth.album.possible': 'Mögliche Erklärung',
  'growth.album.encounter': 'Aus deinem letzten Spiel',
  'growth.album.before': 'Vor diesem Zug · Schritt {{step}}',
  'growth.album.board':
    'Gespeichertes Feld vor Schritt {{step}}. Das vollständige Feld mit Kandidaten ist im Replay verfügbar.',
  'growth.album.replay': 'Diesen Zug ansehen',
  'growth.album.replayProcess': 'Diesen Ablauf ansehen',
  'growth.album.history': 'Frühere Begegnungen',
  'growth.album.numbers': 'Zahlen & Meilensteine',
  'growth.album.technique': 'Über diese Technik',
  'growth.album.source': 'Grundlage des Eintrags',
  'growth.album.noSample': 'Platz für deine nächste Begegnung',
  'growth.album.noSampleBody':
    'Ein passender Zug aus deinen eigenen Spielen wird hier erscheinen.',
  'growth.album.unavailable': 'Keine gespeicherte Vorschau für diesen Eintrag',
  'growth.album.sourceLine': '{{date}} · Level {{level}}',
} as const;
