export const albumEnglish = {
  'growth.footprint.stepMissing': 'Step unavailable',
  'growth.time.now': 'Just now',
  'growth.time.minute': '1 minute ago',
  'growth.time.minutes': '{{count}} minutes ago',
  'growth.time.hour': '1 hour ago',
  'growth.time.hours': '{{count}} hours ago',
  'growth.time.day': '1 day ago',
  'growth.time.days': '{{count}} days ago',
  'growth.time.week': '1 week ago',
  'growth.footprint.stepPosition': 'Step {{step}}/{{total}}',
  'growth.footprint.step': 'Step',
  'growth.footprint.filter': 'Filter',
  'growth.footprint.filterAll': 'All',
  'growth.footprint.learning': 'Learning',
  'growth.footprint.applications': 'Used',
  'growth.footprint.possible': 'Maybe used',
  'growth.footprint.technique': 'Technique',
  'growth.footprint.type': 'Record',
  'growth.footprint.activity': 'Activity',
  'growth.footprint.game': 'Game',
  'growth.footprint.level': 'Level',
  'growth.footprint.alternatives': 'Alternatives',
  'growth.footprint.missing': 'Not saved',
  'growth.footprint.close': 'Close',
  'growth.footprint.end': 'All records shown',
  'growth.footprint.source': 'Record source',

  'growth.entry.remember': 'A moment to revisit',
  'growth.entry.all': 'See all footprints',
  'growth.entry.recent': 'Recent encounters',
  'growth.entry.empty': 'No technique records yet',
  'growth.entry.start': 'Your games will leave their traces here',
  'growth.entry.pending': 'Organizing this game’s records…',
  'growth.entry.failed': 'Records are unavailable for now',
  'growth.entry.incomplete': 'Some evidence is unavailable',
  'growth.entry.fromGame': 'From this game',
  'growth.entry.count': '{{count}} records',
  'growth.entry.preview': 'Preview this record',
  'growth.entry.previewAbove': 'The preview is at the top of this page',
  'growth.entry.noMatch': 'No records in this category',
  'growth.entry.pendingTitle': 'Records are on their way',
  'growth.entry.pendingBody':
    'Saved learning records appear here while applications are being organized.',
  'growth.entry.emptyBody': 'You can still revisit the full game.',

  'growth.album.subtitle': 'Patterns from your games',
  'growth.album.recent': 'Recent',
  'growth.album.all': 'All 39',
  'growth.album.following': 'Following',
  'growth.album.learning': 'Learning contact',
  'growth.album.application': 'Application recorded',
  'growth.album.possible': 'Possible explanation',
  'growth.album.encounter': 'From your recent game',
  'growth.album.before': 'Before this step · Step {{step}}',
  'growth.album.board':
    'Saved board before step {{step}}. Open replay to inspect the full board and candidates.',
  'growth.album.replay': 'Revisit this step',
  'growth.album.replayProcess': 'Revisit this process',
  'growth.album.history': 'Past encounters',
  'growth.album.numbers': 'Numbers & milestones',
  'growth.album.technique': 'About this technique',
  'growth.album.source': 'Record source',
  'growth.album.noSample': 'Your next encounter belongs here',
  'growth.album.noSampleBody':
    'A step from your own games will appear here when one is recorded.',
  'growth.album.unavailable': 'No saved preview for this record',
  'growth.album.sourceLine': '{{date}} · Level {{level}}',
} as const;
export const albumChinese = {
  'growth.footprint.stepMissing': '步骤未记录',
  'growth.time.now': '刚刚',
  'growth.time.minute': '1分钟前',
  'growth.time.minutes': '{{count}}分钟前',
  'growth.time.hour': '1小时前',
  'growth.time.hours': '{{count}}小时前',
  'growth.time.day': '1天前',
  'growth.time.days': '{{count}}天前',
  'growth.time.week': '1周前',
  'growth.footprint.stepPosition': '第{{step}}/{{total}}步',
  'growth.footprint.step': '步骤',
  'growth.footprint.filter': '筛选',
  'growth.footprint.filterAll': '全部',
  'growth.footprint.learning': '学习',
  'growth.footprint.applications': '用过',
  'growth.footprint.possible': '可能用过',
  'growth.footprint.technique': '技巧',
  'growth.footprint.type': '类型',
  'growth.footprint.activity': '活动时间',
  'growth.footprint.game': '对局时间',
  'growth.footprint.level': '难度',
  'growth.footprint.alternatives': '其他候选',
  'growth.footprint.missing': '未记录',
  'growth.footprint.close': '关闭',
  'growth.footprint.end': '已显示全部记录',
  'growth.footprint.source': '记录来源',

  'growth.entry.remember': '本局值得回看',
  'growth.entry.all': '查看全部足迹',
  'growth.entry.recent': '最近的技巧经历',
  'growth.entry.empty': '本局暂无技巧记录',
  'growth.entry.start': '从你的下一局开始积累',
  'growth.entry.pending': '正在整理本局记录…',
  'growth.entry.failed': '暂时无法更新记录',
  'growth.entry.incomplete': '部分记录证据不完整',
  'growth.entry.fromGame': '在这局遇见',
  'growth.entry.count': '{{count}}条记录',
  'growth.entry.preview': '预览这条记录',
  'growth.entry.previewAbove': '预览已更新到页面顶部',
  'growth.entry.noMatch': '这一类暂无记录',
  'growth.entry.pendingTitle': '本局足迹正在整理',
  'growth.entry.pendingBody': '已保存的学习记录会先出现，应用记录稍后更新。',
  'growth.entry.emptyBody': '仍可进入完整复盘，回看这局棋。',

  'growth.album.subtitle': '在你的棋盘上，遇见技巧',
  'growth.album.recent': '最近',
  'growth.album.all': '全部39项',
  'growth.album.following': '已关注',
  'growth.album.learning': '学习接触',
  'growth.album.application': '有应用记录',
  'growth.album.possible': '可能解释',
  'growth.album.encounter': '最近在这局遇见',
  'growth.album.before': '操作前 · 第{{step}}步',
  'growth.album.board':
    '第{{step}}步操作前的真实棋盘。进入复盘可查看完整棋盘和候选数。',
  'growth.album.replay': '回看这一步',
  'growth.album.replayProcess': '回看这个过程',
  'growth.album.history': '过往记录',
  'growth.album.numbers': '统计与里程碑',
  'growth.album.technique': '了解这个技巧',
  'growth.album.source': '查看依据',
  'growth.album.noSample': '下一次遇见，就留在这里',
  'growth.album.noSampleBody':
    '当你的对局留下相关记录，这里会出现属于你的那一步。',
  'growth.album.unavailable': '这条记录没有可恢复的预览',
  'growth.album.sourceLine': '{{date}} · Level {{level}}',
} as const;
export const albumJapanese = {
  'growth.footprint.stepMissing': '手順の記録なし',
  'growth.time.now': 'たった今',
  'growth.time.minute': '1分前',
  'growth.time.minutes': '{{count}}分前',
  'growth.time.hour': '1時間前',
  'growth.time.hours': '{{count}}時間前',
  'growth.time.day': '1日前',
  'growth.time.days': '{{count}}日前',
  'growth.time.week': '1週間前',
  'growth.footprint.stepPosition': '{{step}}/{{total}}手目',
  'growth.footprint.step': '手順',
  'growth.footprint.filter': '絞り込み',
  'growth.footprint.filterAll': 'すべて',
  'growth.footprint.learning': '学び',
  'growth.footprint.applications': '使った',
  'growth.footprint.possible': '使ったかも',
  'growth.footprint.technique': '技法',
  'growth.footprint.type': '種類',
  'growth.footprint.activity': '記録日時',
  'growth.footprint.game': '対局日時',
  'growth.footprint.level': 'レベル',
  'growth.footprint.alternatives': '他の候補',
  'growth.footprint.missing': '未記録',
  'growth.footprint.close': '閉じる',
  'growth.footprint.end': 'すべての記録を表示しました',
  'growth.footprint.source': '記録の出典',

  'growth.entry.remember': 'この対局を振り返る',
  'growth.entry.all': 'すべての記録を見る',
  'growth.entry.recent': '最近の技法との出会い',
  'growth.entry.empty': '技法の記録はまだありません',
  'growth.entry.start': '次の対局から記録を残そう',
  'growth.entry.pending': '対局の記録を整理中…',
  'growth.entry.failed': '記録を更新できません',
  'growth.entry.incomplete': '一部の根拠がありません',
  'growth.entry.fromGame': 'この対局での出会い',
  'growth.entry.count': '{{count}}件の記録',
  'growth.entry.preview': 'この記録をプレビュー',
  'growth.entry.previewAbove': 'ページ上部のプレビューを更新しました',
  'growth.entry.noMatch': 'この種類の記録はありません',
  'growth.entry.pendingTitle': '対局の記録を整理中',
  'growth.entry.pendingBody':
    '保存した学習記録を先に表示し、活用の記録は後で更新します。',
  'growth.entry.emptyBody': '対局全体のリプレイは引き続き見られます。',

  'growth.album.subtitle': '自分の盤面で出会った技法',
  'growth.album.recent': '最近',
  'growth.album.all': '全39技法',
  'growth.album.following': 'フォロー中',
  'growth.album.learning': '学習の記録',
  'growth.album.application': '活用の記録あり',
  'growth.album.possible': '可能な説明',
  'growth.album.encounter': '最近の対局から',
  'growth.album.before': '操作前 · {{step}}手目',
  'growth.album.board':
    '{{step}}手目の直前に保存された盤面。候補を含む全体はリプレイで確認できます。',
  'growth.album.replay': 'この手を振り返る',
  'growth.album.replayProcess': 'この過程を振り返る',
  'growth.album.history': '過去の記録',
  'growth.album.numbers': '統計と節目',
  'growth.album.technique': 'この技法について',
  'growth.album.source': '記録の根拠',
  'growth.album.noSample': '次の出会いをここに',
  'growth.album.noSampleBody':
    '自分の対局で関連する手が記録されると、ここに表示されます。',
  'growth.album.unavailable': 'この記録の盤面プレビューはありません',
  'growth.album.sourceLine': '{{date}} · レベル{{level}}',
} as const;
export const albumGerman = {
  'growth.footprint.stepMissing': 'Schritt fehlt',
  'growth.time.now': 'Gerade eben',
  'growth.time.minute': 'Vor 1 Minute',
  'growth.time.minutes': 'Vor {{count}} Minuten',
  'growth.time.hour': 'Vor 1 Stunde',
  'growth.time.hours': 'Vor {{count}} Stunden',
  'growth.time.day': 'Vor 1 Tag',
  'growth.time.days': 'Vor {{count}} Tagen',
  'growth.time.week': 'Vor 1 Woche',
  'growth.footprint.stepPosition': 'Schritt {{step}}/{{total}}',
  'growth.footprint.step': 'Schritt',
  'growth.footprint.filter': 'Filter',
  'growth.footprint.filterAll': 'Alle',
  'growth.footprint.learning': 'Lernen',
  'growth.footprint.applications': 'Genutzt',
  'growth.footprint.possible': 'Vielleicht genutzt',
  'growth.footprint.technique': 'Technik',
  'growth.footprint.type': 'Eintrag',
  'growth.footprint.activity': 'Aktivität',
  'growth.footprint.game': 'Partie',
  'growth.footprint.level': 'Level',
  'growth.footprint.alternatives': 'Alternativen',
  'growth.footprint.missing': 'Nicht erfasst',
  'growth.footprint.close': 'Schließen',
  'growth.footprint.end': 'Alle Einträge angezeigt',
  'growth.footprint.source': 'Quelle',

  'growth.entry.remember': 'Ein Moment zum Wiederansehen',
  'growth.entry.all': 'Alle Spuren ansehen',
  'growth.entry.recent': 'Letzte Begegnungen',
  'growth.entry.empty': 'Noch keine Technikeinträge',
  'growth.entry.start': 'Dein nächstes Spiel hinterlässt Spuren',
  'growth.entry.pending': 'Einträge werden geordnet…',
  'growth.entry.failed': 'Einträge derzeit nicht verfügbar',
  'growth.entry.incomplete': 'Einige Belege fehlen',
  'growth.entry.fromGame': 'Aus diesem Spiel',
  'growth.entry.count': '{{count}} Einträge',
  'growth.entry.preview': 'Diesen Eintrag ansehen',
  'growth.entry.previewAbove': 'Die Vorschau oben wurde aktualisiert',
  'growth.entry.noMatch': 'Keine Einträge in dieser Kategorie',
  'growth.entry.pendingTitle': 'Spielspuren werden geordnet',
  'growth.entry.pendingBody':
    'Gespeicherte Lernkontakte erscheinen zuerst, Anwendungen folgen später.',
  'growth.entry.emptyBody': 'Du kannst weiterhin das ganze Spiel wiederholen.',

  'growth.album.subtitle': 'Muster aus deinen Spielen',
  'growth.album.recent': 'Zuletzt',
  'growth.album.all': 'Alle 39',
  'growth.album.following': 'Gemerkte',
  'growth.album.learning': 'Lernkontakt',
  'growth.album.application': 'Anwendung erfasst',
  'growth.album.possible': 'Mögliche Erklärung',
  'growth.album.encounter': 'Aus deinem letzten Spiel',
  'growth.album.before': 'Vor diesem Zug · Schritt {{step}}',
  'growth.album.board':
    'Gespeichertes Feld vor Schritt {{step}}. Das vollständige Feld mit Kandidaten ist im Replay verfügbar.',
  'growth.album.replay': 'Diesen Zug ansehen',
  'growth.album.replayProcess': 'Diesen Ablauf ansehen',
  'growth.album.history': 'Frühere Begegnungen',
  'growth.album.numbers': 'Zahlen & Meilensteine',
  'growth.album.technique': 'Über diese Technik',
  'growth.album.source': 'Grundlage des Eintrags',
  'growth.album.noSample': 'Platz für deine nächste Begegnung',
  'growth.album.noSampleBody':
    'Ein passender Zug aus deinen eigenen Spielen wird hier erscheinen.',
  'growth.album.unavailable': 'Keine gespeicherte Vorschau für diesen Eintrag',
  'growth.album.sourceLine': '{{date}} · Level {{level}}',
} as const;
