import { ProductLocale } from '../application';

export const english = {
  'app.loading': 'Preparing offline puzzles…',
  'app.working': 'Working…',
  'app.failureTitle': 'Unable to open your Sudoku data',
  'app.failureBody':
    'Your saved game is safe. Close the app and try again. If the problem continues, reinstall the current build.',
  'app.dismissMessage': 'Dismiss message',
  'app.cancel': 'Cancel',
  'app.back': 'Back',
  'modal.replace.title': 'Start Level {{level}}?',
  'modal.replace.body':
    'Your current game will be recorded as abandoned. This cannot be undone.',
  'modal.replace.confirm': 'Abandon and start',
  'modal.quickDraft.title': 'Regenerate quick draft?',
  'modal.quickDraft.body':
    'The board has changed. Regenerating replaces the saved quick draft and uses one quick-pencil credit.',
  'modal.quickDraft.confirm': 'Regenerate',
  'home.eyebrow': 'OFFLINE LOGIC GAME',
  'home.title': 'Hard Sudoku',
  'home.subtitle': 'Five levels. One clear next step. No account required.',
  'home.continue': 'CONTINUE',
  'home.chooseLevel': 'Choose a level',
  'home.level': 'Level {{level}}',
  'home.startLevel': 'Start Level {{level}}',
  'home.completed': '{{count}} completed',
  'home.solved': 'Solved',
  'home.attempts': 'Attempts',
  'home.hints': 'Hints',
  'home.settings': 'Settings',
  'home.developmentOnly': 'DEVELOPMENT ONLY',
  'home.hintLab': 'Hint Lab · 39 Techniques',
  'home.statistics': 'Statistics',
  'home.help': 'How to play',
  'home.techniques': 'Sudoku academy',
  'home.more': 'More',
  'home.closeMore': 'Close more functions',
  'home.moreFunctions': 'More functions',
  'home.developerTools': 'DEVELOPER TOOLS',
  'home.debugCredits': 'Set debug credits to 999',
  'home.debugCreditBalance':
    'Smart hints: {{hints}} · Quick pencils: {{pencils}}',
  'home.premium': 'Premium',
  'home.comingSoon': 'Coming soon',
  'home.resumeHeroTitle': 'Continue your reasoning',
  'home.newHeroTitle': 'Ready for a new puzzle?',
  'home.focusSubtitle': 'Offline, focused and solved by logic.',
  'home.newGame': 'New game',
  'home.newGameHint': 'Choose Level 1–5',
  'home.progressPercent': '{{progress}}% complete',
  'home.resumeTime': 'Playing time {{time}}',
  'home.offlineNote': 'Offline · No account required',
  'home.closeLevelPicker': 'Close level selection',
  'home.chooseLevelSubtitle': 'Choose the kind of logic you want to practice.',
  'home.levelDescription1': 'Essential singles and foundations',
  'home.levelDescription2': 'Core candidate techniques',
  'home.levelDescription3': 'Intermediate patterns and interactions',
  'home.levelDescription4': 'Advanced combinations',
  'home.levelDescription5': 'Expert chains and deep logic',
  'statistics.title': 'Statistics',
  'statistics.subtitle': 'Your progress is stored only on this device.',
  'statistics.attempts': 'Attempts',
  'statistics.completions': 'Completed',
  'statistics.completionRate': 'Completion rate',
  'statistics.failures': 'Ended after mistakes',
  'statistics.abandonments': 'Abandoned',
  'statistics.totalTime': 'Total play time',
  'statistics.hintsUsed': 'Smart hints used',
  'statistics.quickPencilsUsed': 'Quick pencils used',
  'statistics.byLevel': 'Completed by level',
  'statistics.hoursMinutes': '{{hours}}h {{minutes}}m',
  'statistics.minutes': '{{minutes}}m',
  'help.title': 'How to play',
  'help.subtitle': 'Everything needed to play without guessing.',
  'help.select.title': 'Select a cell',
  'help.select.body':
    'Tap an empty cell, then choose a digit. In digit-first mode, choose the digit before the cell.',
  'help.enter.title': 'Enter a digit',
  'help.enter.body':
    'Each row, column and 3×3 box must contain the digits 1–9 exactly once.',
  'help.candidates.title': 'Candidate notes',
  'help.candidates.body':
    'Use Pencil to add or remove possible digits. Quick pencil creates a complete candidate draft.',
  'help.eraseUndo.title': 'Erase and undo',
  'help.eraseUndo.body':
    'Erase clears the selected entry or notes. Undo reverses your latest board action.',
  'help.pause.title': 'Pause and resume',
  'help.pause.body':
    'Pausing hides the board and stops active play. You can safely continue an unfinished puzzle from Home.',
  'help.mistakes.title': 'Mistakes',
  'help.mistakes.body':
    'Automatic checking can mark wrong entries. The optional three-mistake rule ends that attempt after the third mistake.',
  'help.hints.title': 'Smart hints',
  'help.hints.body':
    'Hints explain one logical next step with focused regions, candidates and visual eliminations before showing the result.',
  'help.complete.title': 'Complete a puzzle',
  'help.complete.body':
    'Fill every cell correctly to finish. Completion, time and tool usage are saved on this device.',
  'techniques.title': 'Sudoku techniques',
  'techniques.subtitle':
    'Explore all 39 logical techniques used by the hint engine, grouped by level.',
  'techniques.level': 'Level {{level}} · {{count}} techniques',
  'techniques.openDetail': 'Open technique details',
  'techniques.goal': 'Goal',
  'techniques.recognition': 'How to recognize it',
  'techniques.result': 'Result type',
  'techniques.code': 'Stable technique code',
  'techniques.genericRegions': 'the relevant unit',
  'techniques.genericCandidates': 'the relevant candidates',
  'techniques.genericDigit': 'the digit being studied',
  'techniques.outcome.placement': 'Place a digit',
  'techniques.outcome.elimination': 'Eliminate candidates',
  'techniques.outcome.both': 'Place or eliminate',
  'techniques.goal.placement':
    'Determine the one digit that must occupy a specific cell.',
  'techniques.goal.elimination':
    'Prove that one or more candidates cannot be true, leaving a simpler board.',
  'techniques.goal.both':
    'Follow the logical links until they force either a placement or a candidate elimination.',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.languageHint': 'Choose the language used by the app.',
  'settings.theme': 'Appearance',
  'settings.themeHint': 'Choose a light, dark or system appearance.',
  'settings.system': 'System',
  'settings.english': 'English',
  'settings.japanese': 'Japanese',
  'settings.german': 'German',
  'settings.simplifiedChinese': 'Simplified Chinese',
  'settings.light': 'Light',
  'settings.dark': 'Dark',
  'settings.on': 'On',
  'settings.off': 'Off',
  'settings.hintAnimations': 'Hint animations',
  'settings.hintAnimationsHint':
    'Animate each visual reasoning step unless the system requests reduced motion.',
  'settings.feedbackDisplay': 'Feedback and display',
  'settings.feedbackDisplayHint':
    'Choose the feedback and information shown while playing.',
  'settings.soundEffects': 'Sound effects',
  'settings.soundEffectsHint': 'Play a short sound for game actions.',
  'settings.haptics': 'Vibration',
  'settings.hapticsHint': 'Vibrate briefly for game actions.',
  'settings.keepAwake': 'Keep screen awake',
  'settings.keepAwakeHint': 'Prevent screen sleep while a game is open.',
  'settings.showTimer': 'Show timer',
  'settings.showTimerHint': 'Display elapsed time above the board.',
  'settings.showRemainingDigits': 'Show remaining digits',
  'settings.showRemainingDigitsHint':
    'Show how many of each digit remain below the number pad.',
  'settings.input': 'Input',
  'settings.inputHint': 'Choose how cells and digits are selected.',
  'settings.cellFirst': 'Cell first',
  'settings.digitFirst': 'Digit first',
  'settings.highlighting': 'Board highlighting',
  'settings.highlightingHint': 'Control visual guidance on the board.',
  'settings.highlightRegions': 'Highlight related regions',
  'settings.highlightRegionsHint':
    'Highlight the selected row, column and box.',
  'settings.highlightSameDigit': 'Highlight matching digits',
  'settings.highlightSameDigitHint':
    'Highlight every placed copy of the selected digit.',
  'settings.gameRules': 'New-game rules',
  'settings.gameRulesHint':
    'These choices apply to newly started games. A resumed game keeps its original rules.',
  'settings.autoCheckErrors': 'Check mistakes automatically',
  'settings.autoCheckErrorsHint':
    'Mark an incorrect entered value immediately.',
  'settings.errorLimit': 'End after three mistakes',
  'settings.errorLimitHint':
    'Automatically enables mistake checking for new games.',
  'settings.autoRemoveCandidates': 'Remove notes automatically',
  'settings.autoRemoveCandidatesHint':
    'Remove peer candidates after entering a value.',
  'game.home': 'Home',
  'game.pause': 'Pause',
  'game.level': 'LEVEL {{level}}',
  'game.mistakes': 'Mistakes {{count}}',
  'game.quickDraft': 'Quick draft',
  'game.manualDraft': 'Manual draft',
  'game.paused': 'GAME PAUSED',
  'game.boardHidden': 'Your board is hidden',
  'game.continue': 'Continue game',
  'game.abandon': 'Abandon this game',
  'game.enterDigit': 'Enter {{digit}}, {{count}} remaining',
  'game.undo': 'Undo',
  'game.erase': 'Erase',
  'game.quick': 'Quick',
  'game.pencil': 'Pencil',
  'game.hint': 'Hint',
  'game.active': 'on',
  'game.remaining': '{{count}} remaining',
  'hint.smart': 'SMART HINT',
  'hint.stepProgress': 'Step {{current}} of {{total}}',
  'hint.close': 'Close',
  'hint.back': 'Back',
  'hint.showResult': 'Show result',
  'hint.showResultAccessibility': 'Show the hint conclusion directly',
  'hint.applying': 'Applying…',
  'hint.applyStep': 'Apply step',
  'hint.next': 'Next',
  'result.complete': 'Puzzle complete',
  'result.ended': 'Attempt ended',
  'result.perfect': 'A clean solve — no mistakes and no smart hints.',
  'result.saved': 'Your progress and rewards are safely stored.',
  'result.failed': 'Try the same puzzle again or choose another level.',
  'result.time': 'Time',
  'result.mistakes': 'Mistakes',
  'result.hints': 'Hints',
  'result.firstReward': 'FIRST COMPLETION REWARD',
  'result.quickReward': 'Quick pencil +{{count}}',
  'result.hintReward': 'Smart hint +{{count}}',
  'result.perfectBonus': 'Perfect bonus',
  'result.streakBonus': 'Streak bonus',
  'result.nextPuzzle': 'Next Level {{level}} puzzle',
  'result.retry': 'Retry this puzzle',
  'result.chooseLevel': 'Choose a new level',
  'board.label': 'Sudoku board',
  'board.cell': 'Row {{row}}, column {{column}}',
  'board.empty': 'empty',
  'board.candidates': 'candidates {{digits}}',
  'board.incorrect': 'incorrect value',
  'board.hintRegion': 'hint focus region',
  'board.hintCell': 'hint focus cell',
  'board.valueEvidence': 'placed value used as hint evidence',
  'board.premise': 'hint premise {{digits}}',
  'board.remove': 'remove candidate {{digits}}',
  'board.ruledOut': 'candidate ruled out {{digits}}',
  'board.place': 'place {{digit}}',
  'board.potential': 'potential pattern cell',
  'board.established': 'established pattern cell',
  'board.affected': 'affected candidate cell',
  'board.result': 'hint result cell',
  'message.game_not_active': 'The game is not active.',
  'message.game_not_paused': 'The game is not paused.',
  'message.hint_in_progress': 'Close or apply the current hint first.',
  'message.no_selected_cell': 'Select an empty cell first.',
  'message.given_cell': 'Given cells cannot be changed.',
  'message.filled_cell': 'Erase the value before editing candidates.',
  'message.nothing_to_erase': 'There is nothing to erase in this cell.',
  'message.nothing_to_undo': 'There are no moves to undo.',
  'message.quick_draft_missing': 'Generate a quick-pencil draft first.',
  'message.incorrect_values':
    'Correct the highlighted value before continuing.',
  'message.conflicting_values':
    'Resolve the conflicting values before continuing.',
  'message.unsolvable_values':
    'This board cannot produce a valid logical step.',
  'message.insufficient_quick_pencil_credits':
    'No quick-pencil credits remain.',
  'message.insufficient_smart_hint_credits': 'No smart-hint credits remain.',
  'message.hint_already_active': 'A hint is already open.',
  'message.no_active_hint': 'There is no hint to apply.',
  'message.invalid_hint': 'The hint no longer matches this board.',
  'message.action_failed': 'The action could not be completed.',
  'message.unexpected_error': 'An unexpected error occurred.',
  'message.board_already_solved': 'This board is already solved.',
  'message.invalid_hint_board':
    'The current board cannot be used for a logical hint.',
  'message.no_supported_hint': 'No supported logical step is available.',
  'message.saved_catalog_changed':
    'The saved game belongs to an older puzzle catalog.',
  'message.saved_puzzle_missing': 'The saved puzzle is no longer available.',
  'message.level_unavailable': 'No Level {{level}} puzzle is available.',
  'message.level_replay':
    'All puzzles at this level are complete. Starting a replay.',
} as const;

export type TranslationKey = keyof typeof english;
export type TranslationResource = Readonly<Record<TranslationKey, string>>;

const japanese: TranslationResource = {
  'app.loading': 'オフラインパズルを準備しています…',
  'app.working': '処理しています…',
  'app.failureTitle': '数独データを開けません',
  'app.failureBody':
    '保存済みのゲームは保護されています。アプリを終了して再試行し、問題が続く場合は現在のビルドを再インストールしてください。',
  'app.dismissMessage': 'メッセージを閉じる',
  'app.cancel': 'キャンセル',
  'app.back': '戻る',
  'modal.replace.title': 'レベル{{level}}を開始しますか？',
  'modal.replace.body':
    '現在のゲームは中断として記録されます。この操作は取り消せません。',
  'modal.replace.confirm': '中断して開始',
  'modal.quickDraft.title': 'クイックメモを再作成しますか？',
  'modal.quickDraft.body':
    '盤面が変更されています。保存済みのクイックメモを置き換え、クレジットを1つ使用します。',
  'modal.quickDraft.confirm': '再作成',
  'home.eyebrow': 'オフライン・ロジックゲーム',
  'home.title': 'Hard Sudoku',
  'home.subtitle': '5段階の難易度。明確な次の一手。アカウント不要。',
  'home.continue': '続ける',
  'home.chooseLevel': 'レベルを選択',
  'home.level': 'レベル {{level}}',
  'home.startLevel': 'レベル{{level}}を開始',
  'home.completed': '{{count}}問クリア',
  'home.solved': 'クリア',
  'home.attempts': '挑戦',
  'home.hints': 'ヒント',
  'home.settings': '設定',
  'home.developmentOnly': '開発専用',
  'home.hintLab': 'ヒントラボ · 39テクニック',
  'home.statistics': '統計',
  'home.help': '遊び方',
  'home.techniques': '数独学習',
  'home.more': 'その他',
  'home.closeMore': 'その他の機能を閉じる',
  'home.moreFunctions': 'その他の機能',
  'home.developerTools': '開発ツール',
  'home.debugCredits': 'デバッグ用クレジットを999にする',
  'home.debugCreditBalance':
    'スマートヒント: {{hints}} · クイックメモ: {{pencils}}',
  'home.premium': 'Premium',
  'home.comingSoon': '近日公開',
  'home.resumeHeroTitle': '推理を続けましょう',
  'home.newHeroTitle': '新しい問題に挑戦しますか？',
  'home.focusSubtitle': 'オフラインで、集中して、論理だけで解く。',
  'home.newGame': '新しいゲーム',
  'home.newGameHint': 'レベル1～5を選択',
  'home.progressPercent': '{{progress}}% 完了',
  'home.resumeTime': 'プレイ時間 {{time}}',
  'home.offlineNote': 'オフライン · アカウント不要',
  'home.closeLevelPicker': 'レベル選択を閉じる',
  'home.chooseLevelSubtitle': '練習したい論理の難しさを選んでください。',
  'home.levelDescription1': '基本のシングルと基礎',
  'home.levelDescription2': '候補数字の基本テクニック',
  'home.levelDescription3': '中級パターンと相互作用',
  'home.levelDescription4': '高度な組み合わせ',
  'home.levelDescription5': 'エキスパート向けチェーンと深い論理',
  'statistics.title': '統計',
  'statistics.subtitle': '進行状況はこの端末にのみ保存されます。',
  'statistics.attempts': '挑戦',
  'statistics.completions': 'クリア',
  'statistics.completionRate': 'クリア率',
  'statistics.failures': 'ミスで終了',
  'statistics.abandonments': '中断',
  'statistics.totalTime': '合計プレイ時間',
  'statistics.hintsUsed': '使用したスマートヒント',
  'statistics.quickPencilsUsed': '使用したクイックメモ',
  'statistics.byLevel': 'レベル別クリア数',
  'statistics.hoursMinutes': '{{hours}}時間{{minutes}}分',
  'statistics.minutes': '{{minutes}}分',
  'help.title': '遊び方',
  'help.subtitle': '推測せずに遊ぶために必要な操作を説明します。',
  'help.select.title': 'マスを選ぶ',
  'help.select.body':
    '空のマスをタップして数字を選びます。数字優先モードでは、数字を選んでからマスをタップします。',
  'help.enter.title': '数字を入れる',
  'help.enter.body':
    '各行、各列、各3×3ブロックに1～9をそれぞれ一度だけ入れます。',
  'help.candidates.title': '候補メモ',
  'help.candidates.body':
    '鉛筆で候補を追加・削除できます。クイックメモは盤面全体の候補を作成します。',
  'help.eraseUndo.title': '消去と元に戻す',
  'help.eraseUndo.body':
    '消去は選択中の数字やメモを消し、元に戻すは直前の盤面操作を取り消します。',
  'help.pause.title': '一時停止と再開',
  'help.pause.body':
    '一時停止すると盤面が隠れます。未完了の問題はホームから安全に再開できます。',
  'help.mistakes.title': 'ミス',
  'help.mistakes.body':
    '自動チェックは誤入力を示します。3回ミスのルールを有効にすると、3回目でその挑戦が終了します。',
  'help.hints.title': 'スマートヒント',
  'help.hints.body':
    '答えを示す前に、注目する領域、候補、除外を使って論理的な次の一手を段階的に説明します。',
  'help.complete.title': '問題を完成する',
  'help.complete.body':
    'すべてのマスを正しく埋めると完成です。結果、時間、ツール使用数はこの端末に保存されます。',
  'techniques.title': '数独テクニック',
  'techniques.subtitle':
    'ヒントエンジンが使う39種類の論理テクニックをレベル別に確認できます。',
  'techniques.level': 'レベル {{level}} · {{count}}種類',
  'techniques.openDetail': 'テクニックの詳細を開く',
  'techniques.goal': '目的',
  'techniques.recognition': '見つけ方',
  'techniques.result': '結果の種類',
  'techniques.code': '安定テクニックコード',
  'techniques.genericRegions': '対象のユニット',
  'techniques.genericCandidates': '対象の候補',
  'techniques.genericDigit': '注目する数字',
  'techniques.outcome.placement': '数字を確定',
  'techniques.outcome.elimination': '候補を除外',
  'techniques.outcome.both': '確定または除外',
  'techniques.goal.placement': '特定のマスに必ず入る1つの数字を確定します。',
  'techniques.goal.elimination':
    '成立しない候補を論理的に除外し、盤面をより単純にします。',
  'techniques.goal.both':
    '論理リンクをたどり、数字の確定または候補の除外を導きます。',
  'settings.title': '設定',
  'settings.language': '言語',
  'settings.languageHint': 'アプリで使用する言語を選択します。',
  'settings.theme': '外観',
  'settings.themeHint': 'ライト、ダーク、またはシステム設定を選択します。',
  'settings.system': 'システム',
  'settings.english': '英語',
  'settings.japanese': '日本語',
  'settings.german': 'ドイツ語',
  'settings.simplifiedChinese': '簡体字中国語',
  'settings.light': 'ライト',
  'settings.dark': 'ダーク',
  'settings.on': 'オン',
  'settings.off': 'オフ',
  'settings.hintAnimations': 'ヒントのアニメーション',
  'settings.hintAnimationsHint':
    'システムの「視差効果を減らす」が有効でない場合、推理の各段階をアニメーション表示します。',
  'settings.feedbackDisplay': 'フィードバックと表示',
  'settings.feedbackDisplayHint': 'プレイ中の反応と表示情報を選びます。',
  'settings.soundEffects': '効果音',
  'settings.soundEffectsHint': 'ゲーム操作時に短い効果音を再生します。',
  'settings.haptics': '振動',
  'settings.hapticsHint': 'ゲーム操作時に短く振動します。',
  'settings.keepAwake': '画面をオンのままにする',
  'settings.keepAwakeHint': 'ゲーム中は画面のスリープを防ぎます。',
  'settings.showTimer': 'タイマーを表示',
  'settings.showTimerHint': '盤面の上に経過時間を表示します。',
  'settings.showRemainingDigits': '残り数字を表示',
  'settings.showRemainingDigitsHint': '各数字の残り個数を表示します。',
  'settings.input': '入力',
  'settings.inputHint': 'マスと数字の選択方法を選びます。',
  'settings.cellFirst': 'マスを先に選択',
  'settings.digitFirst': '数字を先に選択',
  'settings.highlighting': '盤面の強調表示',
  'settings.highlightingHint': '盤面上の視覚的な案内を調整します。',
  'settings.highlightRegions': '関連領域を強調',
  'settings.highlightRegionsHint': '選択した行、列、ボックスを強調します。',
  'settings.highlightSameDigit': '同じ数字を強調',
  'settings.highlightSameDigitHint':
    '選択した数字と同じ数字をすべて強調します。',
  'settings.gameRules': '新規ゲームのルール',
  'settings.gameRulesHint':
    '新しく開始するゲームに適用されます。再開したゲームは元のルールを保持します。',
  'settings.autoCheckErrors': 'ミスを自動チェック',
  'settings.autoCheckErrorsHint': '間違った数字をすぐに表示します。',
  'settings.errorLimit': '3回のミスで終了',
  'settings.errorLimitHint': '新規ゲームでミスの自動チェックも有効にします。',
  'settings.autoRemoveCandidates': 'メモを自動削除',
  'settings.autoRemoveCandidatesHint':
    '数字を入力後、関連マスの候補を削除します。',
  'game.home': 'ホーム',
  'game.pause': '一時停止',
  'game.level': 'レベル {{level}}',
  'game.mistakes': 'ミス {{count}}',
  'game.quickDraft': 'クイックメモ',
  'game.manualDraft': '手動メモ',
  'game.paused': '一時停止中',
  'game.boardHidden': '盤面を非表示にしています',
  'game.continue': 'ゲームを続ける',
  'game.abandon': 'このゲームを中断',
  'game.enterDigit': '{{digit}}を入力、残り{{count}}個',
  'game.undo': '元に戻す',
  'game.erase': '消去',
  'game.quick': 'クイック',
  'game.pencil': 'メモ',
  'game.hint': 'ヒント',
  'game.active': 'オン',
  'game.remaining': '残り{{count}}',
  'hint.smart': 'スマートヒント',
  'hint.stepProgress': '{{total}}ステップ中{{current}}',
  'hint.close': '閉じる',
  'hint.back': '戻る',
  'hint.showResult': '結果を見る',
  'hint.showResultAccessibility': 'ヒントの結論を直接表示',
  'hint.applying': '適用中…',
  'hint.applyStep': 'この手を適用',
  'hint.next': '次へ',
  'result.complete': 'パズル完成',
  'result.ended': '挑戦終了',
  'result.perfect': 'ミスもスマートヒントもない完璧なクリアです。',
  'result.saved': '進行状況と報酬を保存しました。',
  'result.failed': '同じ問題に再挑戦するか、別のレベルを選んでください。',
  'result.time': 'タイム',
  'result.mistakes': 'ミス',
  'result.hints': 'ヒント',
  'result.firstReward': '初回クリア報酬',
  'result.quickReward': 'クイックメモ +{{count}}',
  'result.hintReward': 'スマートヒント +{{count}}',
  'result.perfectBonus': 'パーフェクトボーナス',
  'result.streakBonus': '連続ボーナス',
  'result.nextPuzzle': '次のレベル{{level}}問題',
  'result.retry': 'この問題に再挑戦',
  'result.chooseLevel': '別のレベルを選ぶ',
  'board.label': '数独盤面',
  'board.cell': '{{row}}行{{column}}列',
  'board.empty': '空きマス',
  'board.candidates': '候補 {{digits}}',
  'board.incorrect': '誤った数字',
  'board.hintRegion': 'ヒントの注目領域',
  'board.hintCell': 'ヒントの注目マス',
  'board.valueEvidence': 'ヒントの根拠となる確定数字',
  'board.premise': 'ヒントの前提 {{digits}}',
  'board.remove': '候補を削除 {{digits}}',
  'board.ruledOut': '除外される候補 {{digits}}',
  'board.place': '{{digit}}を入力',
  'board.potential': 'パターン候補のマス',
  'board.established': '確定したパターンのマス',
  'board.affected': '影響を受ける候補のマス',
  'board.result': 'ヒント結果のマス',
  'message.game_not_active': 'ゲームは進行中ではありません。',
  'message.game_not_paused': 'ゲームは一時停止されていません。',
  'message.hint_in_progress': '現在のヒントを閉じるか適用してください。',
  'message.no_selected_cell': '空きマスを選択してください。',
  'message.given_cell': '最初からある数字は変更できません。',
  'message.filled_cell': '候補を編集する前に数字を消してください。',
  'message.nothing_to_erase': 'このマスには消すものがありません。',
  'message.nothing_to_undo': '元に戻せる操作がありません。',
  'message.quick_draft_missing': '先にクイックメモを作成してください。',
  'message.incorrect_values': '強調された誤りを直してから続けてください。',
  'message.conflicting_values': '重複している数字を解消してください。',
  'message.unsolvable_values': 'この盤面から有効な論理手順を作成できません。',
  'message.insufficient_quick_pencil_credits':
    'クイックメモの回数が残っていません。',
  'message.insufficient_smart_hint_credits':
    'スマートヒントの回数が残っていません。',
  'message.hint_already_active': 'ヒントはすでに開いています。',
  'message.no_active_hint': '適用できるヒントがありません。',
  'message.invalid_hint': 'ヒントが現在の盤面と一致しません。',
  'message.action_failed': '操作を完了できませんでした。',
  'message.unexpected_error': '予期しないエラーが発生しました。',
  'message.board_already_solved': 'この盤面はすでに完成しています。',
  'message.invalid_hint_board': '現在の盤面では論理ヒントを使用できません。',
  'message.no_supported_hint': '対応している論理手順が見つかりません。',
  'message.saved_catalog_changed': '保存したゲームは古い問題集のものです。',
  'message.saved_puzzle_missing': '保存した問題は利用できなくなりました。',
  'message.level_unavailable': 'レベル{{level}}の問題がありません。',
  'message.level_replay':
    'このレベルはすべて完成済みです。再挑戦を開始します。',
};

const german: TranslationResource = {
  'app.loading': 'Offline-Rätsel werden vorbereitet…',
  'app.working': 'Wird verarbeitet…',
  'app.failureTitle': 'Die Sudoku-Daten konnten nicht geöffnet werden',
  'app.failureBody':
    'Dein gespeichertes Spiel ist sicher. Schließe die App und versuche es erneut. Falls das Problem bleibt, installiere den aktuellen Build neu.',
  'app.dismissMessage': 'Nachricht schließen',
  'app.cancel': 'Abbrechen',
  'app.back': 'Zurück',
  'modal.replace.title': 'Level {{level}} starten?',
  'modal.replace.body':
    'Das aktuelle Spiel wird als abgebrochen gespeichert. Dies kann nicht rückgängig gemacht werden.',
  'modal.replace.confirm': 'Abbrechen und starten',
  'modal.quickDraft.title': 'Schnellnotizen neu erstellen?',
  'modal.quickDraft.body':
    'Das Spielfeld hat sich geändert. Die gespeicherten Schnellnotizen werden ersetzt und ein Guthaben wird verwendet.',
  'modal.quickDraft.confirm': 'Neu erstellen',
  'home.eyebrow': 'OFFLINE-LOGIKSPIEL',
  'home.title': 'Hard Sudoku',
  'home.subtitle':
    'Fünf Level. Ein klarer nächster Schritt. Kein Konto erforderlich.',
  'home.continue': 'FORTSETZEN',
  'home.chooseLevel': 'Level auswählen',
  'home.level': 'Level {{level}}',
  'home.startLevel': 'Level {{level}} starten',
  'home.completed': '{{count}} abgeschlossen',
  'home.solved': 'Gelöst',
  'home.attempts': 'Versuche',
  'home.hints': 'Hinweise',
  'home.settings': 'Einstellungen',
  'home.developmentOnly': 'NUR ENTWICKLUNG',
  'home.hintLab': 'Hinweis-Labor · 39 Techniken',
  'home.statistics': 'Statistik',
  'home.help': 'Spielanleitung',
  'home.techniques': 'Sudoku-Akademie',
  'home.more': 'Mehr',
  'home.closeMore': 'Weitere Funktionen schließen',
  'home.moreFunctions': 'Weitere Funktionen',
  'home.developerTools': 'ENTWICKLERWERKZEUGE',
  'home.debugCredits': 'Testguthaben auf 999 setzen',
  'home.debugCreditBalance':
    'Hinweise: {{hints}} · Schnellnotizen: {{pencils}}',
  'home.premium': 'Premium',
  'home.comingSoon': 'Demnächst verfügbar',
  'home.resumeHeroTitle': 'Setze deine Logik fort',
  'home.newHeroTitle': 'Bereit für ein neues Rätsel?',
  'home.focusSubtitle': 'Offline, konzentriert und logisch gelöst.',
  'home.newGame': 'Neues Spiel',
  'home.newGameHint': 'Level 1–5 auswählen',
  'home.progressPercent': '{{progress}} % abgeschlossen',
  'home.resumeTime': 'Spielzeit {{time}}',
  'home.offlineNote': 'Offline · Kein Konto erforderlich',
  'home.closeLevelPicker': 'Levelauswahl schließen',
  'home.chooseLevelSubtitle':
    'Wähle die Art von Logik, die du trainieren möchtest.',
  'home.levelDescription1': 'Grundlegende Singles und Grundlagen',
  'home.levelDescription2': 'Zentrale Kandidatentechniken',
  'home.levelDescription3': 'Mittlere Muster und Wechselwirkungen',
  'home.levelDescription4': 'Fortgeschrittene Kombinationen',
  'home.levelDescription5': 'Expertenketten und tiefe Logik',
  'statistics.title': 'Statistik',
  'statistics.subtitle':
    'Dein Fortschritt wird nur auf diesem Gerät gespeichert.',
  'statistics.attempts': 'Versuche',
  'statistics.completions': 'Abgeschlossen',
  'statistics.completionRate': 'Abschlussquote',
  'statistics.failures': 'Nach Fehlern beendet',
  'statistics.abandonments': 'Abgebrochen',
  'statistics.totalTime': 'Gesamte Spielzeit',
  'statistics.hintsUsed': 'Verwendete Hinweise',
  'statistics.quickPencilsUsed': 'Verwendete Schnellnotizen',
  'statistics.byLevel': 'Abschlüsse nach Level',
  'statistics.hoursMinutes': '{{hours}} Std. {{minutes}} Min.',
  'statistics.minutes': '{{minutes}} Min.',
  'help.title': 'Spielanleitung',
  'help.subtitle': 'Alles, was du zum Spielen ohne Raten brauchst.',
  'help.select.title': 'Zelle auswählen',
  'help.select.body':
    'Tippe auf eine leere Zelle und wähle eine Ziffer. Im Ziffer-zuerst-Modus wählst du zuerst die Ziffer.',
  'help.enter.title': 'Ziffer eintragen',
  'help.enter.body':
    'Jede Zeile, Spalte und jedes 3×3-Feld muss die Ziffern 1 bis 9 genau einmal enthalten.',
  'help.candidates.title': 'Kandidatennotizen',
  'help.candidates.body':
    'Mit dem Stift fügst du mögliche Ziffern hinzu oder entfernst sie. Schnellnotiz erstellt alle Kandidaten.',
  'help.eraseUndo.title': 'Löschen und rückgängig',
  'help.eraseUndo.body':
    'Löschen entfernt den gewählten Eintrag oder Notizen. Rückgängig kehrt den letzten Spielzug um.',
  'help.pause.title': 'Pause und Fortsetzen',
  'help.pause.body':
    'In der Pause wird das Feld verborgen. Ein unfertiges Sudoku kann sicher von der Startseite fortgesetzt werden.',
  'help.mistakes.title': 'Fehler',
  'help.mistakes.body':
    'Die automatische Prüfung markiert falsche Einträge. Die optionale Drei-Fehler-Regel beendet dann den Versuch.',
  'help.hints.title': 'Smarte Hinweise',
  'help.hints.body':
    'Hinweise erklären vor dem Ergebnis einen logischen Schritt mit Fokusbereichen, Kandidaten und sichtbaren Ausschlüssen.',
  'help.complete.title': 'Sudoku abschließen',
  'help.complete.body':
    'Fülle alle Zellen korrekt. Abschluss, Zeit und Werkzeugnutzung werden auf diesem Gerät gespeichert.',
  'techniques.title': 'Sudoku-Techniken',
  'techniques.subtitle':
    'Entdecke alle 39 logischen Techniken der Hinweis-Engine, nach Level gruppiert.',
  'techniques.level': 'Level {{level}} · {{count}} Techniken',
  'techniques.openDetail': 'Details der Technik öffnen',
  'techniques.goal': 'Ziel',
  'techniques.recognition': 'Erkennung',
  'techniques.result': 'Ergebnistyp',
  'techniques.code': 'Stabiler Technikcode',
  'techniques.genericRegions': 'der relevanten Einheit',
  'techniques.genericCandidates': 'die relevanten Kandidaten',
  'techniques.genericDigit': 'die untersuchte Ziffer',
  'techniques.outcome.placement': 'Ziffer setzen',
  'techniques.outcome.elimination': 'Kandidaten entfernen',
  'techniques.outcome.both': 'Setzen oder entfernen',
  'techniques.goal.placement':
    'Bestimme die einzige Ziffer, die in einer bestimmten Zelle stehen muss.',
  'techniques.goal.elimination':
    'Beweise, dass Kandidaten nicht stimmen können, und vereinfache so das Feld.',
  'techniques.goal.both':
    'Verfolge logische Verknüpfungen, bis sie eine Setzung oder Entfernung erzwingen.',
  'settings.title': 'Einstellungen',
  'settings.language': 'Sprache',
  'settings.languageHint': 'Wähle die Sprache der App.',
  'settings.theme': 'Darstellung',
  'settings.themeHint': 'Wähle Hell, Dunkel oder die Systemeinstellung.',
  'settings.system': 'System',
  'settings.english': 'Englisch',
  'settings.japanese': 'Japanisch',
  'settings.german': 'Deutsch',
  'settings.simplifiedChinese': 'Vereinfachtes Chinesisch',
  'settings.light': 'Hell',
  'settings.dark': 'Dunkel',
  'settings.on': 'Ein',
  'settings.off': 'Aus',
  'settings.hintAnimations': 'Hinweisanimationen',
  'settings.hintAnimationsHint':
    'Animiert jeden Denkschritt, sofern das System keine reduzierten Bewegungen verlangt.',
  'settings.feedbackDisplay': 'Feedback und Anzeige',
  'settings.feedbackDisplayHint':
    'Lege Rückmeldungen und angezeigte Informationen beim Spielen fest.',
  'settings.soundEffects': 'Soundeffekte',
  'settings.soundEffectsHint': 'Kurzen Ton bei Spielaktionen wiedergeben.',
  'settings.haptics': 'Vibration',
  'settings.hapticsHint': 'Bei Spielaktionen kurz vibrieren.',
  'settings.keepAwake': 'Bildschirm eingeschaltet lassen',
  'settings.keepAwakeHint': 'Verhindert den Ruhezustand während eines Spiels.',
  'settings.showTimer': 'Timer anzeigen',
  'settings.showTimerHint': 'Spielzeit oberhalb des Spielfelds anzeigen.',
  'settings.showRemainingDigits': 'Verbleibende Ziffern anzeigen',
  'settings.showRemainingDigitsHint':
    'Verbleibende Anzahl unter jeder Ziffer anzeigen.',
  'settings.input': 'Eingabe',
  'settings.inputHint': 'Lege die Auswahlreihenfolge von Feld und Ziffer fest.',
  'settings.cellFirst': 'Feld zuerst',
  'settings.digitFirst': 'Ziffer zuerst',
  'settings.highlighting': 'Spielfeld-Hervorhebung',
  'settings.highlightingHint': 'Steuert visuelle Orientierung im Spielfeld.',
  'settings.highlightRegions': 'Zugehörige Bereiche hervorheben',
  'settings.highlightRegionsHint':
    'Zeile, Spalte und Block des Feldes hervorheben.',
  'settings.highlightSameDigit': 'Gleiche Ziffern hervorheben',
  'settings.highlightSameDigitHint':
    'Alle gesetzten gleichen Ziffern hervorheben.',
  'settings.gameRules': 'Regeln für neue Spiele',
  'settings.gameRulesHint':
    'Gilt für neu gestartete Spiele. Fortgesetzte Spiele behalten ihre bisherigen Regeln.',
  'settings.autoCheckErrors': 'Fehler automatisch prüfen',
  'settings.autoCheckErrorsHint': 'Falsche Eingaben sofort markieren.',
  'settings.errorLimit': 'Nach drei Fehlern beenden',
  'settings.errorLimitHint':
    'Aktiviert bei neuen Spielen automatisch die Fehlerprüfung.',
  'settings.autoRemoveCandidates': 'Notizen automatisch entfernen',
  'settings.autoRemoveCandidatesHint':
    'Kandidaten in zugehörigen Feldern nach einer Eingabe entfernen.',
  'game.home': 'Start',
  'game.pause': 'Pause',
  'game.level': 'LEVEL {{level}}',
  'game.mistakes': 'Fehler {{count}}',
  'game.quickDraft': 'Schnellnotizen',
  'game.manualDraft': 'Eigene Notizen',
  'game.paused': 'SPIEL PAUSIERT',
  'game.boardHidden': 'Das Spielfeld ist ausgeblendet',
  'game.continue': 'Spiel fortsetzen',
  'game.abandon': 'Dieses Spiel abbrechen',
  'game.enterDigit': '{{digit}} eingeben, {{count}} verbleibend',
  'game.undo': 'Rückgängig',
  'game.erase': 'Löschen',
  'game.quick': 'Schnell',
  'game.pencil': 'Notizen',
  'game.hint': 'Hinweis',
  'game.active': 'ein',
  'game.remaining': '{{count}} verbleibend',
  'hint.smart': 'INTELLIGENTER HINWEIS',
  'hint.stepProgress': 'Schritt {{current}} von {{total}}',
  'hint.close': 'Schließen',
  'hint.back': 'Zurück',
  'hint.showResult': 'Ergebnis zeigen',
  'hint.showResultAccessibility': 'Hinweisergebnis direkt anzeigen',
  'hint.applying': 'Wird angewendet…',
  'hint.applyStep': 'Schritt anwenden',
  'hint.next': 'Weiter',
  'result.complete': 'Rätsel gelöst',
  'result.ended': 'Versuch beendet',
  'result.perfect':
    'Fehlerfrei gelöst — ohne Fehler und intelligente Hinweise.',
  'result.saved': 'Fortschritt und Belohnungen wurden sicher gespeichert.',
  'result.failed':
    'Versuche dasselbe Rätsel erneut oder wähle ein anderes Level.',
  'result.time': 'Zeit',
  'result.mistakes': 'Fehler',
  'result.hints': 'Hinweise',
  'result.firstReward': 'BELOHNUNG FÜR ERSTES LÖSEN',
  'result.quickReward': 'Schnellnotiz +{{count}}',
  'result.hintReward': 'Intelligenter Hinweis +{{count}}',
  'result.perfectBonus': 'Perfekt-Bonus',
  'result.streakBonus': 'Serienbonus',
  'result.nextPuzzle': 'Nächstes Rätsel in Level {{level}}',
  'result.retry': 'Dieses Rätsel erneut versuchen',
  'result.chooseLevel': 'Neues Level auswählen',
  'board.label': 'Sudoku-Spielfeld',
  'board.cell': 'Zeile {{row}}, Spalte {{column}}',
  'board.empty': 'leer',
  'board.candidates': 'Kandidaten {{digits}}',
  'board.incorrect': 'falscher Wert',
  'board.hintRegion': 'Hinweis-Fokusbereich',
  'board.hintCell': 'Hinweis-Fokusfeld',
  'board.valueEvidence': 'gesetzter Wert als Hinweisbeleg',
  'board.premise': 'Hinweisvoraussetzung {{digits}}',
  'board.remove': 'Kandidat entfernen {{digits}}',
  'board.ruledOut': 'ausgeschlossener Kandidat {{digits}}',
  'board.place': '{{digit}} setzen',
  'board.potential': 'mögliches Musterfeld',
  'board.established': 'bestätigtes Musterfeld',
  'board.affected': 'betroffenes Kandidatenfeld',
  'board.result': 'Hinweisergebnisfeld',
  'message.game_not_active': 'Das Spiel ist nicht aktiv.',
  'message.game_not_paused': 'Das Spiel ist nicht pausiert.',
  'message.hint_in_progress':
    'Schließe oder übernimm zuerst den aktuellen Hinweis.',
  'message.no_selected_cell': 'Wähle zuerst ein leeres Feld.',
  'message.given_cell': 'Vorgegebene Felder können nicht geändert werden.',
  'message.filled_cell': 'Lösche den Wert, bevor du Kandidaten bearbeitest.',
  'message.nothing_to_erase': 'In diesem Feld gibt es nichts zu löschen.',
  'message.nothing_to_undo': 'Es gibt keinen Zug zum Rückgängigmachen.',
  'message.quick_draft_missing': 'Erstelle zuerst Schnellnotizen.',
  'message.incorrect_values':
    'Korrigiere den markierten Wert, bevor du fortfährst.',
  'message.conflicting_values': 'Löse zuerst die widersprüchlichen Werte auf.',
  'message.unsolvable_values':
    'Dieses Spielfeld erlaubt keinen gültigen logischen Schritt.',
  'message.insufficient_quick_pencil_credits':
    'Keine Schnellnotiz-Guthaben mehr verfügbar.',
  'message.insufficient_smart_hint_credits':
    'Keine Hinweis-Guthaben mehr verfügbar.',
  'message.hint_already_active': 'Ein Hinweis ist bereits geöffnet.',
  'message.no_active_hint': 'Es gibt keinen Hinweis zum Anwenden.',
  'message.invalid_hint': 'Der Hinweis passt nicht mehr zum Spielfeld.',
  'message.action_failed': 'Die Aktion konnte nicht abgeschlossen werden.',
  'message.unexpected_error': 'Ein unerwarteter Fehler ist aufgetreten.',
  'message.board_already_solved': 'Dieses Spielfeld ist bereits gelöst.',
  'message.invalid_hint_board':
    'Für dieses Spielfeld ist kein logischer Hinweis möglich.',
  'message.no_supported_hint':
    'Kein unterstützter logischer Schritt verfügbar.',
  'message.saved_catalog_changed':
    'Das gespeicherte Spiel gehört zu einem älteren Rätselkatalog.',
  'message.saved_puzzle_missing':
    'Das gespeicherte Rätsel ist nicht mehr verfügbar.',
  'message.level_unavailable': 'Für Level {{level}} ist kein Rätsel verfügbar.',
  'message.level_replay':
    'Alle Rätsel dieses Levels sind gelöst. Eine Wiederholung beginnt.',
};

const simplifiedChinese: TranslationResource = {
  'app.loading': '正在准备离线题库…',
  'app.working': '正在处理…',
  'app.failureTitle': '无法打开数独数据',
  'app.failureBody':
    '已保存的游戏不会受影响。请关闭应用后重试；如果问题持续，请重新安装当前构建版本。',
  'app.dismissMessage': '关闭消息',
  'app.cancel': '取消',
  'app.back': '返回',
  'modal.replace.title': '开始 Level {{level}}？',
  'modal.replace.body': '当前游戏将被记录为放弃，并且无法撤销。',
  'modal.replace.confirm': '放弃并开始',
  'modal.quickDraft.title': '重新生成快速铅笔？',
  'modal.quickDraft.body':
    '棋盘已经变化。重新生成会替换已保存的快速铅笔，并消耗一次额度。',
  'modal.quickDraft.confirm': '重新生成',
  'home.eyebrow': '离线逻辑游戏',
  'home.title': 'Hard Sudoku',
  'home.subtitle': '五个难度等级，每一步都有清晰逻辑，无需账号。',
  'home.continue': '继续',
  'home.chooseLevel': '选择难度',
  'home.level': 'Level {{level}}',
  'home.startLevel': '开始 Level {{level}}',
  'home.completed': '已完成 {{count}} 题',
  'home.solved': '完成',
  'home.attempts': '尝试',
  'home.hints': '提示',
  'home.settings': '设置',
  'home.developmentOnly': '仅限开发环境',
  'home.hintLab': '提示实验室 · 39 种技巧',
  'home.statistics': '统计',
  'home.help': '玩法说明',
  'home.techniques': '数独学堂',
  'home.more': '更多',
  'home.closeMore': '关闭更多功能',
  'home.moreFunctions': '更多功能',
  'home.developerTools': '开发工具',
  'home.debugCredits': '将调试额度补充到 999',
  'home.debugCreditBalance': '智能提示：{{hints}} · 快速铅笔：{{pencils}}',
  'home.premium': 'Premium',
  'home.comingSoon': '即将推出',
  'home.resumeHeroTitle': '继续你的推理',
  'home.newHeroTitle': '准备开始新的挑战？',
  'home.focusSubtitle': '离线、专注，只用逻辑解题。',
  'home.newGame': '新游戏',
  'home.newGameHint': '选择 Level 1–5',
  'home.progressPercent': '已完成 {{progress}}%',
  'home.resumeTime': '游戏时间 {{time}}',
  'home.offlineNote': '离线游戏 · 无需账号',
  'home.closeLevelPicker': '关闭难度选择',
  'home.chooseLevelSubtitle': '选择你想要练习的逻辑难度。',
  'home.levelDescription1': '基础唯一数与入门逻辑',
  'home.levelDescription2': '核心候选数技巧',
  'home.levelDescription3': '中级模式与区域交互',
  'home.levelDescription4': '高级组合技巧',
  'home.levelDescription5': '专家链与深度逻辑',
  'statistics.title': '统计',
  'statistics.subtitle': '你的游戏进度仅保存在这台设备上。',
  'statistics.attempts': '尝试',
  'statistics.completions': '完成',
  'statistics.completionRate': '完成率',
  'statistics.failures': '错误超限',
  'statistics.abandonments': '放弃',
  'statistics.totalTime': '总游戏时间',
  'statistics.hintsUsed': '已用智能提示',
  'statistics.quickPencilsUsed': '已用快速铅笔',
  'statistics.byLevel': '各难度完成数',
  'statistics.hoursMinutes': '{{hours}} 小时 {{minutes}} 分钟',
  'statistics.minutes': '{{minutes}} 分钟',
  'help.title': '玩法说明',
  'help.subtitle': '掌握无需猜测即可完成数独的全部操作。',
  'help.select.title': '选择单元格',
  'help.select.body':
    '点击空白单元格，再选择数字。使用数字优先模式时，先选数字，再点击单元格。',
  'help.enter.title': '填写数字',
  'help.enter.body': '每一行、每一列和每个 3×3 宫都必须恰好包含一次数字 1–9。',
  'help.candidates.title': '候选笔记',
  'help.candidates.body':
    '使用铅笔添加或删除可能的数字；快速铅笔可以生成完整的候选数草稿。',
  'help.eraseUndo.title': '擦除与撤销',
  'help.eraseUndo.body':
    '擦除会清除选中格的数字或笔记；撤销会还原最近一次棋盘操作。',
  'help.pause.title': '暂停与继续',
  'help.pause.body': '暂停时棋盘会隐藏。未完成的题目可以安全地从首页继续。',
  'help.mistakes.title': '错误',
  'help.mistakes.body':
    '自动检查可以标出错误输入；可选的三次错误规则会在第三次错误后结束本次尝试。',
  'help.hints.title': '智能提示',
  'help.hints.body':
    '提示会先用聚焦区域、候选数和可视化排除逐步解释一个逻辑步骤，最后才显示结果。',
  'help.complete.title': '完成题目',
  'help.complete.body':
    '正确填满所有单元格即可完成。完成结果、用时和工具使用情况会保存在本机。',
  'techniques.title': '数独技巧',
  'techniques.subtitle': '按难度查看提示引擎使用的全部 39 种逻辑技巧。',
  'techniques.level': 'Level {{level}} · {{count}} 种技巧',
  'techniques.openDetail': '打开技巧详情',
  'techniques.goal': '目标',
  'techniques.recognition': '识别方法',
  'techniques.result': '结果类型',
  'techniques.code': '稳定技巧代码',
  'techniques.genericRegions': '相关区域',
  'techniques.genericCandidates': '相关候选数',
  'techniques.genericDigit': '正在研究的数字',
  'techniques.outcome.placement': '确定数字',
  'techniques.outcome.elimination': '排除候选数',
  'techniques.outcome.both': '确定数字或排除候选数',
  'techniques.goal.placement': '确定某个单元格中唯一必然成立的数字。',
  'techniques.goal.elimination':
    '证明一个或多个候选数不可能成立，让盘面变得更简单。',
  'techniques.goal.both': '沿逻辑链推理，直到必然确定数字或排除候选数。',
  'settings.title': '设置',
  'settings.language': '语言',
  'settings.languageHint': '选择应用使用的语言。',
  'settings.theme': '外观',
  'settings.themeHint': '选择浅色、深色或跟随系统。',
  'settings.system': '跟随系统',
  'settings.english': '英语',
  'settings.japanese': '日语',
  'settings.german': '德语',
  'settings.simplifiedChinese': '简体中文',
  'settings.light': '浅色',
  'settings.dark': '深色',
  'settings.on': '开启',
  'settings.off': '关闭',
  'settings.hintAnimations': '提示动画',
  'settings.hintAnimationsHint':
    '逐步播放视觉推理；如果系统要求减少动态效果，则自动停用动画。',
  'settings.feedbackDisplay': '反馈与显示',
  'settings.feedbackDisplayHint': '选择游戏时的操作反馈和显示信息。',
  'settings.soundEffects': '音效',
  'settings.soundEffectsHint': '游戏操作时播放简短音效。',
  'settings.haptics': '震动',
  'settings.hapticsHint': '游戏操作时轻微震动。',
  'settings.keepAwake': '保持屏幕常亮',
  'settings.keepAwakeHint': '打开游戏时防止屏幕自动休眠。',
  'settings.showTimer': '显示计时器',
  'settings.showTimerHint': '在棋盘上方显示已用时间。',
  'settings.showRemainingDigits': '显示剩余数字',
  'settings.showRemainingDigitsHint': '在数字键下方显示剩余数量。',
  'settings.input': '输入方式',
  'settings.inputHint': '选择先点单元格还是先点数字。',
  'settings.cellFirst': '选格优先',
  'settings.digitFirst': '数字优先',
  'settings.highlighting': '棋盘高亮',
  'settings.highlightingHint': '控制棋盘上的视觉引导。',
  'settings.highlightRegions': '高亮相关区域',
  'settings.highlightRegionsHint': '高亮当前格所在的行、列和宫。',
  'settings.highlightSameDigit': '高亮相同数字',
  'settings.highlightSameDigitHint': '高亮棋盘上所有相同的已填数字。',
  'settings.gameRules': '新游戏规则',
  'settings.gameRulesHint': '仅对新开始的游戏生效；恢复的游戏保留原有规则。',
  'settings.autoCheckErrors': '自动检查错误',
  'settings.autoCheckErrorsHint': '填入错误数字时立即标记。',
  'settings.errorLimit': '三次错误结束本局',
  'settings.errorLimitHint': '新游戏开启后会同时强制开启自动检查。',
  'settings.autoRemoveCandidates': '自动删除候选数',
  'settings.autoRemoveCandidatesHint': '填入数字后删除相关格中的同数候选。',
  'game.home': '首页',
  'game.pause': '暂停',
  'game.level': 'LEVEL {{level}}',
  'game.mistakes': '错误 {{count}}',
  'game.quickDraft': '快速候选',
  'game.manualDraft': '手动候选',
  'game.paused': '游戏已暂停',
  'game.boardHidden': '棋盘已隐藏',
  'game.continue': '继续游戏',
  'game.abandon': '放弃本局',
  'game.enterDigit': '填入 {{digit}}，还剩 {{count}} 个',
  'game.undo': '撤销',
  'game.erase': '擦除',
  'game.quick': '快速铅笔',
  'game.pencil': '铅笔',
  'game.hint': '提示',
  'game.active': '已开启',
  'game.remaining': '剩余 {{count}} 次',
  'hint.smart': '智能提示',
  'hint.stepProgress': '第 {{current}} / {{total}} 步',
  'hint.close': '关闭',
  'hint.back': '上一步',
  'hint.showResult': '查看结果',
  'hint.showResultAccessibility': '直接查看提示结论',
  'hint.applying': '正在应用…',
  'hint.applyStep': '应用这一步',
  'hint.next': '下一步',
  'result.complete': '完成题目',
  'result.ended': '本次尝试结束',
  'result.perfect': '完美完成——没有错误，也没有使用智能提示。',
  'result.saved': '进度和奖励已安全保存。',
  'result.failed': '可以重试当前题目，或选择其他难度。',
  'result.time': '用时',
  'result.mistakes': '错误',
  'result.hints': '提示',
  'result.firstReward': '首次完成奖励',
  'result.quickReward': '快速铅笔 +{{count}}',
  'result.hintReward': '智能提示 +{{count}}',
  'result.perfectBonus': '完美奖励',
  'result.streakBonus': '连续完成奖励',
  'result.nextPuzzle': '下一道 Level {{level}} 题目',
  'result.retry': '重试当前题目',
  'result.chooseLevel': '选择其他难度',
  'board.label': '数独棋盘',
  'board.cell': '第 {{row}} 行，第 {{column}} 列',
  'board.empty': '空格',
  'board.candidates': '候选数 {{digits}}',
  'board.incorrect': '错误数字',
  'board.hintRegion': '提示聚焦区域',
  'board.hintCell': '提示聚焦单元格',
  'board.valueEvidence': '作为提示依据的已填数字',
  'board.premise': '推理前提 {{digits}}',
  'board.remove': '删除候选数 {{digits}}',
  'board.ruledOut': '被排除的候选数 {{digits}}',
  'board.place': '填入 {{digit}}',
  'board.potential': '潜在模式单元格',
  'board.established': '已成立模式单元格',
  'board.affected': '受影响候选单元格',
  'board.result': '提示结果单元格',
  'message.game_not_active': '游戏当前未进行。',
  'message.game_not_paused': '游戏当前未暂停。',
  'message.hint_in_progress': '请先关闭或应用当前提示。',
  'message.no_selected_cell': '请先选择一个空格。',
  'message.given_cell': '题目给定的数字不能修改。',
  'message.filled_cell': '编辑候选数前请先擦除已填数字。',
  'message.nothing_to_erase': '这个单元格没有可擦除的内容。',
  'message.nothing_to_undo': '当前没有可以撤销的操作。',
  'message.quick_draft_missing': '请先生成快速候选。',
  'message.incorrect_values': '请先改正高亮显示的错误数字。',
  'message.conflicting_values': '请先解决相互冲突的数字。',
  'message.unsolvable_values': '当前盘面无法产生有效的逻辑步骤。',
  'message.insufficient_quick_pencil_credits': '快速铅笔额度已经用完。',
  'message.insufficient_smart_hint_credits': '智能提示额度已经用完。',
  'message.hint_already_active': '当前已经打开了一个提示。',
  'message.no_active_hint': '当前没有可以应用的提示。',
  'message.invalid_hint': '提示已经与当前盘面不匹配。',
  'message.action_failed': '无法完成这个操作。',
  'message.unexpected_error': '发生了意外错误。',
  'message.board_already_solved': '当前棋盘已经完成。',
  'message.invalid_hint_board': '当前盘面不能用于生成逻辑提示。',
  'message.no_supported_hint': '当前没有可用的受支持逻辑步骤。',
  'message.saved_catalog_changed': '保存的游戏属于旧版本题库。',
  'message.saved_puzzle_missing': '保存的题目已经不可用。',
  'message.level_unavailable': '当前没有 Level {{level}} 的题目。',
  'message.level_replay': '这个难度的题目已经全部完成，开始重复挑战。',
};

export const TRANSLATIONS: Readonly<
  Record<ProductLocale, TranslationResource>
> = {
  en: english,
  ja: japanese,
  de: german,
  'zh-Hans': simplifiedChinese,
};
