import { ProductLocale } from '../application';

export const english = {
  'app.loading': 'Preparing offline puzzles…',
  'app.failureTitle': 'Unable to open your Sudoku data',
  'app.failureBody':
    'Your saved game is safe. Close the app and try again. If the problem continues, reinstall the current build.',
  'app.dismissMessage': 'Dismiss message',
  'app.cancel': 'Cancel',
  'app.back': 'Back',
  'modal.replace.title': 'Start Level {{level}}?',
  'modal.replace.body':
    'Your current game will be recorded as abandoned. This cannot be undone.',
  'modal.replace.confirm': 'Abandon and start',
  'modal.quickDraft.title': 'Regenerate quick draft?',
  'modal.quickDraft.body':
    'The board has changed. Regenerating replaces the saved quick draft and uses one quick-pencil credit.',
  'modal.quickDraft.confirm': 'Regenerate',
  'home.eyebrow': 'OFFLINE LOGIC GAME',
  'home.title': 'Hard Sudoku',
  'home.subtitle': 'Five levels. One clear next step. No account required.',
  'home.continue': 'CONTINUE',
  'home.chooseLevel': 'Choose a level',
  'home.level': 'Level {{level}}',
  'home.startLevel': 'Start Level {{level}}',
  'home.completed': '{{count}} completed',
  'home.solved': 'Solved',
  'home.attempts': 'Attempts',
  'home.hints': 'Hints',
  'home.settings': 'Settings',
  'home.developmentOnly': 'DEVELOPMENT ONLY',
  'home.hintLab': 'Hint Lab · 39 Techniques',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.languageHint': 'Choose the language used by the app.',
  'settings.theme': 'Appearance',
  'settings.themeHint': 'Choose a light, dark or system appearance.',
  'settings.system': 'System',
  'settings.english': 'English',
  'settings.japanese': 'Japanese',
  'settings.german': 'German',
  'settings.simplifiedChinese': 'Simplified Chinese',
  'settings.light': 'Light',
  'settings.dark': 'Dark',
  'settings.on': 'On',
  'settings.off': 'Off',
  'settings.hintAnimations': 'Hint animations',
  'settings.hintAnimationsHint':
    'Animate each visual reasoning step unless the system requests reduced motion.',
  'settings.feedbackDisplay': 'Feedback and display',
  'settings.feedbackDisplayHint':
    'Choose the feedback and information shown while playing.',
  'settings.soundEffects': 'Sound effects',
  'settings.soundEffectsHint': 'Play a short sound for game actions.',
  'settings.haptics': 'Vibration',
  'settings.hapticsHint': 'Vibrate briefly for game actions.',
  'settings.keepAwake': 'Keep screen awake',
  'settings.keepAwakeHint': 'Prevent screen sleep while a game is open.',
  'settings.showTimer': 'Show timer',
  'settings.showTimerHint': 'Display elapsed time above the board.',
  'settings.showRemainingDigits': 'Show remaining digits',
  'settings.showRemainingDigitsHint':
    'Show how many of each digit remain below the number pad.',
  'settings.input': 'Input',
  'settings.inputHint': 'Choose how cells and digits are selected.',
  'settings.cellFirst': 'Cell first',
  'settings.digitFirst': 'Digit first',
  'settings.highlighting': 'Board highlighting',
  'settings.highlightingHint': 'Control visual guidance on the board.',
  'settings.highlightRegions': 'Highlight related regions',
  'settings.highlightRegionsHint':
    'Highlight the selected row, column and box.',
  'settings.highlightSameDigit': 'Highlight matching digits',
  'settings.highlightSameDigitHint':
    'Highlight every placed copy of the selected digit.',
  'settings.gameRules': 'New-game rules',
  'settings.gameRulesHint':
    'These choices apply to newly started games. A resumed game keeps its original rules.',
  'settings.autoCheckErrors': 'Check mistakes automatically',
  'settings.autoCheckErrorsHint':
    'Mark an incorrect entered value immediately.',
  'settings.errorLimit': 'End after three mistakes',
  'settings.errorLimitHint':
    'Automatically enables mistake checking for new games.',
  'settings.autoRemoveCandidates': 'Remove notes automatically',
  'settings.autoRemoveCandidatesHint':
    'Remove peer candidates after entering a value.',
  'game.home': 'Home',
  'game.pause': 'Pause',
  'game.level': 'LEVEL {{level}}',
  'game.mistakes': 'Mistakes {{count}}',
  'game.quickDraft': 'Quick draft',
  'game.manualDraft': 'Manual draft',
  'game.paused': 'GAME PAUSED',
  'game.boardHidden': 'Your board is hidden',
  'game.continue': 'Continue game',
  'game.abandon': 'Abandon this game',
  'game.enterDigit': 'Enter {{digit}}, {{count}} remaining',
  'game.undo': 'Undo',
  'game.erase': 'Erase',
  'game.quick': 'Quick',
  'game.pencil': 'Pencil',
  'game.hint': 'Hint',
  'game.active': 'on',
  'game.remaining': '{{count}} remaining',
  'hint.smart': 'SMART HINT',
  'hint.stepProgress': 'Step {{current}} of {{total}}',
  'hint.close': 'Close',
  'hint.back': 'Back',
  'hint.showResult': 'Show result',
  'hint.showResultAccessibility': 'Show the hint conclusion directly',
  'hint.applying': 'Applying…',
  'hint.applyStep': 'Apply step',
  'hint.next': 'Next',
  'result.complete': 'Puzzle complete',
  'result.ended': 'Attempt ended',
  'result.perfect': 'A clean solve — no mistakes and no smart hints.',
  'result.saved': 'Your progress and rewards are safely stored.',
  'result.failed': 'Try the same puzzle again or choose another level.',
  'result.time': 'Time',
  'result.mistakes': 'Mistakes',
  'result.hints': 'Hints',
  'result.firstReward': 'FIRST COMPLETION REWARD',
  'result.quickReward': 'Quick pencil +{{count}}',
  'result.hintReward': 'Smart hint +{{count}}',
  'result.perfectBonus': 'Perfect bonus',
  'result.streakBonus': 'Streak bonus',
  'result.nextPuzzle': 'Next Level {{level}} puzzle',
  'result.retry': 'Retry this puzzle',
  'result.chooseLevel': 'Choose a new level',
  'board.label': 'Sudoku board',
  'board.cell': 'Row {{row}}, column {{column}}',
  'board.empty': 'empty',
  'board.candidates': 'candidates {{digits}}',
  'board.incorrect': 'incorrect value',
  'board.hintRegion': 'hint focus region',
  'board.hintCell': 'hint focus cell',
  'board.valueEvidence': 'placed value used as hint evidence',
  'board.premise': 'hint premise {{digits}}',
  'board.remove': 'remove candidate {{digits}}',
  'board.ruledOut': 'candidate ruled out {{digits}}',
  'board.place': 'place {{digit}}',
  'board.potential': 'potential pattern cell',
  'board.established': 'established pattern cell',
  'board.affected': 'affected candidate cell',
  'board.result': 'hint result cell',
  'message.game_not_active': 'The game is not active.',
  'message.game_not_paused': 'The game is not paused.',
  'message.hint_in_progress': 'Close or apply the current hint first.',
  'message.no_selected_cell': 'Select an empty cell first.',
  'message.given_cell': 'Given cells cannot be changed.',
  'message.filled_cell': 'Erase the value before editing candidates.',
  'message.nothing_to_erase': 'There is nothing to erase in this cell.',
  'message.nothing_to_undo': 'There are no moves to undo.',
  'message.quick_draft_missing': 'Generate a quick-pencil draft first.',
  'message.incorrect_values':
    'Correct the highlighted value before continuing.',
  'message.conflicting_values':
    'Resolve the conflicting values before continuing.',
  'message.unsolvable_values':
    'This board cannot produce a valid logical step.',
  'message.insufficient_quick_pencil_credits':
    'No quick-pencil credits remain.',
  'message.insufficient_smart_hint_credits': 'No smart-hint credits remain.',
  'message.hint_already_active': 'A hint is already open.',
  'message.no_active_hint': 'There is no hint to apply.',
  'message.invalid_hint': 'The hint no longer matches this board.',
  'message.action_failed': 'The action could not be completed.',
  'message.unexpected_error': 'An unexpected error occurred.',
  'message.board_already_solved': 'This board is already solved.',
  'message.invalid_hint_board':
    'The current board cannot be used for a logical hint.',
  'message.no_supported_hint': 'No supported logical step is available.',
  'message.saved_catalog_changed':
    'The saved game belongs to an older puzzle catalog.',
  'message.saved_puzzle_missing': 'The saved puzzle is no longer available.',
  'message.level_unavailable': 'No Level {{level}} puzzle is available.',
  'message.level_replay':
    'All puzzles at this level are complete. Starting a replay.',
} as const;

export type TranslationKey = keyof typeof english;
export type TranslationResource = Readonly<Record<TranslationKey, string>>;

const japanese: TranslationResource = {
  'app.loading': 'オフラインパズルを準備しています…',
  'app.failureTitle': '数独データを開けません',
  'app.failureBody':
    '保存済みのゲームは保護されています。アプリを終了して再試行し、問題が続く場合は現在のビルドを再インストールしてください。',
  'app.dismissMessage': 'メッセージを閉じる',
  'app.cancel': 'キャンセル',
  'app.back': '戻る',
  'modal.replace.title': 'レベル{{level}}を開始しますか？',
  'modal.replace.body':
    '現在のゲームは中断として記録されます。この操作は取り消せません。',
  'modal.replace.confirm': '中断して開始',
  'modal.quickDraft.title': 'クイックメモを再作成しますか？',
  'modal.quickDraft.body':
    '盤面が変更されています。保存済みのクイックメモを置き換え、クレジットを1つ使用します。',
  'modal.quickDraft.confirm': '再作成',
  'home.eyebrow': 'オフライン・ロジックゲーム',
  'home.title': 'Hard Sudoku',
  'home.subtitle': '5段階の難易度。明確な次の一手。アカウント不要。',
  'home.continue': '続ける',
  'home.chooseLevel': 'レベルを選択',
  'home.level': 'レベル {{level}}',
  'home.startLevel': 'レベル{{level}}を開始',
  'home.completed': '{{count}}問クリア',
  'home.solved': 'クリア',
  'home.attempts': '挑戦',
  'home.hints': 'ヒント',
  'home.settings': '設定',
  'home.developmentOnly': '開発専用',
  'home.hintLab': 'ヒントラボ · 39テクニック',
  'settings.title': '設定',
  'settings.language': '言語',
  'settings.languageHint': 'アプリで使用する言語を選択します。',
  'settings.theme': '外観',
  'settings.themeHint': 'ライト、ダーク、またはシステム設定を選択します。',
  'settings.system': 'システム',
  'settings.english': '英語',
  'settings.japanese': '日本語',
  'settings.german': 'ドイツ語',
  'settings.simplifiedChinese': '簡体字中国語',
  'settings.light': 'ライト',
  'settings.dark': 'ダーク',
  'settings.on': 'オン',
  'settings.off': 'オフ',
  'settings.hintAnimations': 'ヒントのアニメーション',
  'settings.hintAnimationsHint':
    'システムの「視差効果を減らす」が有効でない場合、推理の各段階をアニメーション表示します。',
  'settings.feedbackDisplay': 'フィードバックと表示',
  'settings.feedbackDisplayHint': 'プレイ中の反応と表示情報を選びます。',
  'settings.soundEffects': '効果音',
  'settings.soundEffectsHint': 'ゲーム操作時に短い効果音を再生します。',
  'settings.haptics': '振動',
  'settings.hapticsHint': 'ゲーム操作時に短く振動します。',
  'settings.keepAwake': '画面をオンのままにする',
  'settings.keepAwakeHint': 'ゲーム中は画面のスリープを防ぎます。',
  'settings.showTimer': 'タイマーを表示',
  'settings.showTimerHint': '盤面の上に経過時間を表示します。',
  'settings.showRemainingDigits': '残り数字を表示',
  'settings.showRemainingDigitsHint': '各数字の残り個数を表示します。',
  'settings.input': '入力',
  'settings.inputHint': 'マスと数字の選択方法を選びます。',
  'settings.cellFirst': 'マスを先に選択',
  'settings.digitFirst': '数字を先に選択',
  'settings.highlighting': '盤面の強調表示',
  'settings.highlightingHint': '盤面上の視覚的な案内を調整します。',
  'settings.highlightRegions': '関連領域を強調',
  'settings.highlightRegionsHint': '選択した行、列、ボックスを強調します。',
  'settings.highlightSameDigit': '同じ数字を強調',
  'settings.highlightSameDigitHint':
    '選択した数字と同じ数字をすべて強調します。',
  'settings.gameRules': '新規ゲームのルール',
  'settings.gameRulesHint':
    '新しく開始するゲームに適用されます。再開したゲームは元のルールを保持します。',
  'settings.autoCheckErrors': 'ミスを自動チェック',
  'settings.autoCheckErrorsHint': '間違った数字をすぐに表示します。',
  'settings.errorLimit': '3回のミスで終了',
  'settings.errorLimitHint': '新規ゲームでミスの自動チェックも有効にします。',
  'settings.autoRemoveCandidates': 'メモを自動削除',
  'settings.autoRemoveCandidatesHint':
    '数字を入力後、関連マスの候補を削除します。',
  'game.home': 'ホーム',
  'game.pause': '一時停止',
  'game.level': 'レベル {{level}}',
  'game.mistakes': 'ミス {{count}}',
  'game.quickDraft': 'クイックメモ',
  'game.manualDraft': '手動メモ',
  'game.paused': '一時停止中',
  'game.boardHidden': '盤面を非表示にしています',
  'game.continue': 'ゲームを続ける',
  'game.abandon': 'このゲームを中断',
  'game.enterDigit': '{{digit}}を入力、残り{{count}}個',
  'game.undo': '元に戻す',
  'game.erase': '消去',
  'game.quick': 'クイック',
  'game.pencil': 'メモ',
  'game.hint': 'ヒント',
  'game.active': 'オン',
  'game.remaining': '残り{{count}}',
  'hint.smart': 'スマートヒント',
  'hint.stepProgress': '{{total}}ステップ中{{current}}',
  'hint.close': '閉じる',
  'hint.back': '戻る',
  'hint.showResult': '結果を見る',
  'hint.showResultAccessibility': 'ヒントの結論を直接表示',
  'hint.applying': '適用中…',
  'hint.applyStep': 'この手を適用',
  'hint.next': '次へ',
  'result.complete': 'パズル完成',
  'result.ended': '挑戦終了',
  'result.perfect': 'ミスもスマートヒントもない完璧なクリアです。',
  'result.saved': '進行状況と報酬を保存しました。',
  'result.failed': '同じ問題に再挑戦するか、別のレベルを選んでください。',
  'result.time': 'タイム',
  'result.mistakes': 'ミス',
  'result.hints': 'ヒント',
  'result.firstReward': '初回クリア報酬',
  'result.quickReward': 'クイックメモ +{{count}}',
  'result.hintReward': 'スマートヒント +{{count}}',
  'result.perfectBonus': 'パーフェクトボーナス',
  'result.streakBonus': '連続ボーナス',
  'result.nextPuzzle': '次のレベル{{level}}問題',
  'result.retry': 'この問題に再挑戦',
  'result.chooseLevel': '別のレベルを選ぶ',
  'board.label': '数独盤面',
  'board.cell': '{{row}}行{{column}}列',
  'board.empty': '空きマス',
  'board.candidates': '候補 {{digits}}',
  'board.incorrect': '誤った数字',
  'board.hintRegion': 'ヒントの注目領域',
  'board.hintCell': 'ヒントの注目マス',
  'board.valueEvidence': 'ヒントの根拠となる確定数字',
  'board.premise': 'ヒントの前提 {{digits}}',
  'board.remove': '候補を削除 {{digits}}',
  'board.ruledOut': '除外される候補 {{digits}}',
  'board.place': '{{digit}}を入力',
  'board.potential': 'パターン候補のマス',
  'board.established': '確定したパターンのマス',
  'board.affected': '影響を受ける候補のマス',
  'board.result': 'ヒント結果のマス',
  'message.game_not_active': 'ゲームは進行中ではありません。',
  'message.game_not_paused': 'ゲームは一時停止されていません。',
  'message.hint_in_progress': '現在のヒントを閉じるか適用してください。',
  'message.no_selected_cell': '空きマスを選択してください。',
  'message.given_cell': '最初からある数字は変更できません。',
  'message.filled_cell': '候補を編集する前に数字を消してください。',
  'message.nothing_to_erase': 'このマスには消すものがありません。',
  'message.nothing_to_undo': '元に戻せる操作がありません。',
  'message.quick_draft_missing': '先にクイックメモを作成してください。',
  'message.incorrect_values': '強調された誤りを直してから続けてください。',
  'message.conflicting_values': '重複している数字を解消してください。',
  'message.unsolvable_values': 'この盤面から有効な論理手順を作成できません。',
  'message.insufficient_quick_pencil_credits':
    'クイックメモの回数が残っていません。',
  'message.insufficient_smart_hint_credits':
    'スマートヒントの回数が残っていません。',
  'message.hint_already_active': 'ヒントはすでに開いています。',
  'message.no_active_hint': '適用できるヒントがありません。',
  'message.invalid_hint': 'ヒントが現在の盤面と一致しません。',
  'message.action_failed': '操作を完了できませんでした。',
  'message.unexpected_error': '予期しないエラーが発生しました。',
  'message.board_already_solved': 'この盤面はすでに完成しています。',
  'message.invalid_hint_board': '現在の盤面では論理ヒントを使用できません。',
  'message.no_supported_hint': '対応している論理手順が見つかりません。',
  'message.saved_catalog_changed': '保存したゲームは古い問題集のものです。',
  'message.saved_puzzle_missing': '保存した問題は利用できなくなりました。',
  'message.level_unavailable': 'レベル{{level}}の問題がありません。',
  'message.level_replay':
    'このレベルはすべて完成済みです。再挑戦を開始します。',
};

const german: TranslationResource = {
  'app.loading': 'Offline-Rätsel werden vorbereitet…',
  'app.failureTitle': 'Die Sudoku-Daten konnten nicht geöffnet werden',
  'app.failureBody':
    'Dein gespeichertes Spiel ist sicher. Schließe die App und versuche es erneut. Falls das Problem bleibt, installiere den aktuellen Build neu.',
  'app.dismissMessage': 'Nachricht schließen',
  'app.cancel': 'Abbrechen',
  'app.back': 'Zurück',
  'modal.replace.title': 'Level {{level}} starten?',
  'modal.replace.body':
    'Das aktuelle Spiel wird als abgebrochen gespeichert. Dies kann nicht rückgängig gemacht werden.',
  'modal.replace.confirm': 'Abbrechen und starten',
  'modal.quickDraft.title': 'Schnellnotizen neu erstellen?',
  'modal.quickDraft.body':
    'Das Spielfeld hat sich geändert. Die gespeicherten Schnellnotizen werden ersetzt und ein Guthaben wird verwendet.',
  'modal.quickDraft.confirm': 'Neu erstellen',
  'home.eyebrow': 'OFFLINE-LOGIKSPIEL',
  'home.title': 'Hard Sudoku',
  'home.subtitle':
    'Fünf Level. Ein klarer nächster Schritt. Kein Konto erforderlich.',
  'home.continue': 'FORTSETZEN',
  'home.chooseLevel': 'Level auswählen',
  'home.level': 'Level {{level}}',
  'home.startLevel': 'Level {{level}} starten',
  'home.completed': '{{count}} abgeschlossen',
  'home.solved': 'Gelöst',
  'home.attempts': 'Versuche',
  'home.hints': 'Hinweise',
  'home.settings': 'Einstellungen',
  'home.developmentOnly': 'NUR ENTWICKLUNG',
  'home.hintLab': 'Hinweis-Labor · 39 Techniken',
  'settings.title': 'Einstellungen',
  'settings.language': 'Sprache',
  'settings.languageHint': 'Wähle die Sprache der App.',
  'settings.theme': 'Darstellung',
  'settings.themeHint': 'Wähle Hell, Dunkel oder die Systemeinstellung.',
  'settings.system': 'System',
  'settings.english': 'Englisch',
  'settings.japanese': 'Japanisch',
  'settings.german': 'Deutsch',
  'settings.simplifiedChinese': 'Vereinfachtes Chinesisch',
  'settings.light': 'Hell',
  'settings.dark': 'Dunkel',
  'settings.on': 'Ein',
  'settings.off': 'Aus',
  'settings.hintAnimations': 'Hinweisanimationen',
  'settings.hintAnimationsHint':
    'Animiert jeden Denkschritt, sofern das System keine reduzierten Bewegungen verlangt.',
  'settings.feedbackDisplay': 'Feedback und Anzeige',
  'settings.feedbackDisplayHint':
    'Lege Rückmeldungen und angezeigte Informationen beim Spielen fest.',
  'settings.soundEffects': 'Soundeffekte',
  'settings.soundEffectsHint': 'Kurzen Ton bei Spielaktionen wiedergeben.',
  'settings.haptics': 'Vibration',
  'settings.hapticsHint': 'Bei Spielaktionen kurz vibrieren.',
  'settings.keepAwake': 'Bildschirm eingeschaltet lassen',
  'settings.keepAwakeHint': 'Verhindert den Ruhezustand während eines Spiels.',
  'settings.showTimer': 'Timer anzeigen',
  'settings.showTimerHint': 'Spielzeit oberhalb des Spielfelds anzeigen.',
  'settings.showRemainingDigits': 'Verbleibende Ziffern anzeigen',
  'settings.showRemainingDigitsHint':
    'Verbleibende Anzahl unter jeder Ziffer anzeigen.',
  'settings.input': 'Eingabe',
  'settings.inputHint': 'Lege die Auswahlreihenfolge von Feld und Ziffer fest.',
  'settings.cellFirst': 'Feld zuerst',
  'settings.digitFirst': 'Ziffer zuerst',
  'settings.highlighting': 'Spielfeld-Hervorhebung',
  'settings.highlightingHint': 'Steuert visuelle Orientierung im Spielfeld.',
  'settings.highlightRegions': 'Zugehörige Bereiche hervorheben',
  'settings.highlightRegionsHint':
    'Zeile, Spalte und Block des Feldes hervorheben.',
  'settings.highlightSameDigit': 'Gleiche Ziffern hervorheben',
  'settings.highlightSameDigitHint':
    'Alle gesetzten gleichen Ziffern hervorheben.',
  'settings.gameRules': 'Regeln für neue Spiele',
  'settings.gameRulesHint':
    'Gilt für neu gestartete Spiele. Fortgesetzte Spiele behalten ihre bisherigen Regeln.',
  'settings.autoCheckErrors': 'Fehler automatisch prüfen',
  'settings.autoCheckErrorsHint': 'Falsche Eingaben sofort markieren.',
  'settings.errorLimit': 'Nach drei Fehlern beenden',
  'settings.errorLimitHint':
    'Aktiviert bei neuen Spielen automatisch die Fehlerprüfung.',
  'settings.autoRemoveCandidates': 'Notizen automatisch entfernen',
  'settings.autoRemoveCandidatesHint':
    'Kandidaten in zugehörigen Feldern nach einer Eingabe entfernen.',
  'game.home': 'Start',
  'game.pause': 'Pause',
  'game.level': 'LEVEL {{level}}',
  'game.mistakes': 'Fehler {{count}}',
  'game.quickDraft': 'Schnellnotizen',
  'game.manualDraft': 'Eigene Notizen',
  'game.paused': 'SPIEL PAUSIERT',
  'game.boardHidden': 'Das Spielfeld ist ausgeblendet',
  'game.continue': 'Spiel fortsetzen',
  'game.abandon': 'Dieses Spiel abbrechen',
  'game.enterDigit': '{{digit}} eingeben, {{count}} verbleibend',
  'game.undo': 'Rückgängig',
  'game.erase': 'Löschen',
  'game.quick': 'Schnell',
  'game.pencil': 'Notizen',
  'game.hint': 'Hinweis',
  'game.active': 'ein',
  'game.remaining': '{{count}} verbleibend',
  'hint.smart': 'INTELLIGENTER HINWEIS',
  'hint.stepProgress': 'Schritt {{current}} von {{total}}',
  'hint.close': 'Schließen',
  'hint.back': 'Zurück',
  'hint.showResult': 'Ergebnis zeigen',
  'hint.showResultAccessibility': 'Hinweisergebnis direkt anzeigen',
  'hint.applying': 'Wird angewendet…',
  'hint.applyStep': 'Schritt anwenden',
  'hint.next': 'Weiter',
  'result.complete': 'Rätsel gelöst',
  'result.ended': 'Versuch beendet',
  'result.perfect':
    'Fehlerfrei gelöst — ohne Fehler und intelligente Hinweise.',
  'result.saved': 'Fortschritt und Belohnungen wurden sicher gespeichert.',
  'result.failed':
    'Versuche dasselbe Rätsel erneut oder wähle ein anderes Level.',
  'result.time': 'Zeit',
  'result.mistakes': 'Fehler',
  'result.hints': 'Hinweise',
  'result.firstReward': 'BELOHNUNG FÜR ERSTES LÖSEN',
  'result.quickReward': 'Schnellnotiz +{{count}}',
  'result.hintReward': 'Intelligenter Hinweis +{{count}}',
  'result.perfectBonus': 'Perfekt-Bonus',
  'result.streakBonus': 'Serienbonus',
  'result.nextPuzzle': 'Nächstes Rätsel in Level {{level}}',
  'result.retry': 'Dieses Rätsel erneut versuchen',
  'result.chooseLevel': 'Neues Level auswählen',
  'board.label': 'Sudoku-Spielfeld',
  'board.cell': 'Zeile {{row}}, Spalte {{column}}',
  'board.empty': 'leer',
  'board.candidates': 'Kandidaten {{digits}}',
  'board.incorrect': 'falscher Wert',
  'board.hintRegion': 'Hinweis-Fokusbereich',
  'board.hintCell': 'Hinweis-Fokusfeld',
  'board.valueEvidence': 'gesetzter Wert als Hinweisbeleg',
  'board.premise': 'Hinweisvoraussetzung {{digits}}',
  'board.remove': 'Kandidat entfernen {{digits}}',
  'board.ruledOut': 'ausgeschlossener Kandidat {{digits}}',
  'board.place': '{{digit}} setzen',
  'board.potential': 'mögliches Musterfeld',
  'board.established': 'bestätigtes Musterfeld',
  'board.affected': 'betroffenes Kandidatenfeld',
  'board.result': 'Hinweisergebnisfeld',
  'message.game_not_active': 'Das Spiel ist nicht aktiv.',
  'message.game_not_paused': 'Das Spiel ist nicht pausiert.',
  'message.hint_in_progress':
    'Schließe oder übernimm zuerst den aktuellen Hinweis.',
  'message.no_selected_cell': 'Wähle zuerst ein leeres Feld.',
  'message.given_cell': 'Vorgegebene Felder können nicht geändert werden.',
  'message.filled_cell': 'Lösche den Wert, bevor du Kandidaten bearbeitest.',
  'message.nothing_to_erase': 'In diesem Feld gibt es nichts zu löschen.',
  'message.nothing_to_undo': 'Es gibt keinen Zug zum Rückgängigmachen.',
  'message.quick_draft_missing': 'Erstelle zuerst Schnellnotizen.',
  'message.incorrect_values':
    'Korrigiere den markierten Wert, bevor du fortfährst.',
  'message.conflicting_values': 'Löse zuerst die widersprüchlichen Werte auf.',
  'message.unsolvable_values':
    'Dieses Spielfeld erlaubt keinen gültigen logischen Schritt.',
  'message.insufficient_quick_pencil_credits':
    'Keine Schnellnotiz-Guthaben mehr verfügbar.',
  'message.insufficient_smart_hint_credits':
    'Keine Hinweis-Guthaben mehr verfügbar.',
  'message.hint_already_active': 'Ein Hinweis ist bereits geöffnet.',
  'message.no_active_hint': 'Es gibt keinen Hinweis zum Anwenden.',
  'message.invalid_hint': 'Der Hinweis passt nicht mehr zum Spielfeld.',
  'message.action_failed': 'Die Aktion konnte nicht abgeschlossen werden.',
  'message.unexpected_error': 'Ein unerwarteter Fehler ist aufgetreten.',
  'message.board_already_solved': 'Dieses Spielfeld ist bereits gelöst.',
  'message.invalid_hint_board':
    'Für dieses Spielfeld ist kein logischer Hinweis möglich.',
  'message.no_supported_hint':
    'Kein unterstützter logischer Schritt verfügbar.',
  'message.saved_catalog_changed':
    'Das gespeicherte Spiel gehört zu einem älteren Rätselkatalog.',
  'message.saved_puzzle_missing':
    'Das gespeicherte Rätsel ist nicht mehr verfügbar.',
  'message.level_unavailable': 'Für Level {{level}} ist kein Rätsel verfügbar.',
  'message.level_replay':
    'Alle Rätsel dieses Levels sind gelöst. Eine Wiederholung beginnt.',
};

const simplifiedChinese: TranslationResource = {
  'app.loading': '正在准备离线题库…',
  'app.failureTitle': '无法打开数独数据',
  'app.failureBody':
    '已保存的游戏不会受影响。请关闭应用后重试；如果问题持续，请重新安装当前构建版本。',
  'app.dismissMessage': '关闭消息',
  'app.cancel': '取消',
  'app.back': '返回',
  'modal.replace.title': '开始 Level {{level}}？',
  'modal.replace.body': '当前游戏将被记录为放弃，并且无法撤销。',
  'modal.replace.confirm': '放弃并开始',
  'modal.quickDraft.title': '重新生成快速铅笔？',
  'modal.quickDraft.body':
    '棋盘已经变化。重新生成会替换已保存的快速铅笔，并消耗一次额度。',
  'modal.quickDraft.confirm': '重新生成',
  'home.eyebrow': '离线逻辑游戏',
  'home.title': 'Hard Sudoku',
  'home.subtitle': '五个难度等级，每一步都有清晰逻辑，无需账号。',
  'home.continue': '继续',
  'home.chooseLevel': '选择难度',
  'home.level': 'Level {{level}}',
  'home.startLevel': '开始 Level {{level}}',
  'home.completed': '已完成 {{count}} 题',
  'home.solved': '完成',
  'home.attempts': '尝试',
  'home.hints': '提示',
  'home.settings': '设置',
  'home.developmentOnly': '仅限开发环境',
  'home.hintLab': '提示实验室 · 39 种技巧',
  'settings.title': '设置',
  'settings.language': '语言',
  'settings.languageHint': '选择应用使用的语言。',
  'settings.theme': '外观',
  'settings.themeHint': '选择浅色、深色或跟随系统。',
  'settings.system': '跟随系统',
  'settings.english': '英语',
  'settings.japanese': '日语',
  'settings.german': '德语',
  'settings.simplifiedChinese': '简体中文',
  'settings.light': '浅色',
  'settings.dark': '深色',
  'settings.on': '开启',
  'settings.off': '关闭',
  'settings.hintAnimations': '提示动画',
  'settings.hintAnimationsHint':
    '逐步播放视觉推理；如果系统要求减少动态效果，则自动停用动画。',
  'settings.feedbackDisplay': '反馈与显示',
  'settings.feedbackDisplayHint': '选择游戏时的操作反馈和显示信息。',
  'settings.soundEffects': '音效',
  'settings.soundEffectsHint': '游戏操作时播放简短音效。',
  'settings.haptics': '震动',
  'settings.hapticsHint': '游戏操作时轻微震动。',
  'settings.keepAwake': '保持屏幕常亮',
  'settings.keepAwakeHint': '打开游戏时防止屏幕自动休眠。',
  'settings.showTimer': '显示计时器',
  'settings.showTimerHint': '在棋盘上方显示已用时间。',
  'settings.showRemainingDigits': '显示剩余数字',
  'settings.showRemainingDigitsHint': '在数字键下方显示剩余数量。',
  'settings.input': '输入方式',
  'settings.inputHint': '选择先点单元格还是先点数字。',
  'settings.cellFirst': '选格优先',
  'settings.digitFirst': '数字优先',
  'settings.highlighting': '棋盘高亮',
  'settings.highlightingHint': '控制棋盘上的视觉引导。',
  'settings.highlightRegions': '高亮相关区域',
  'settings.highlightRegionsHint': '高亮当前格所在的行、列和宫。',
  'settings.highlightSameDigit': '高亮相同数字',
  'settings.highlightSameDigitHint': '高亮棋盘上所有相同的已填数字。',
  'settings.gameRules': '新游戏规则',
  'settings.gameRulesHint': '仅对新开始的游戏生效；恢复的游戏保留原有规则。',
  'settings.autoCheckErrors': '自动检查错误',
  'settings.autoCheckErrorsHint': '填入错误数字时立即标记。',
  'settings.errorLimit': '三次错误结束本局',
  'settings.errorLimitHint': '新游戏开启后会同时强制开启自动检查。',
  'settings.autoRemoveCandidates': '自动删除候选数',
  'settings.autoRemoveCandidatesHint': '填入数字后删除相关格中的同数候选。',
  'game.home': '首页',
  'game.pause': '暂停',
  'game.level': 'LEVEL {{level}}',
  'game.mistakes': '错误 {{count}}',
  'game.quickDraft': '快速候选',
  'game.manualDraft': '手动候选',
  'game.paused': '游戏已暂停',
  'game.boardHidden': '棋盘已隐藏',
  'game.continue': '继续游戏',
  'game.abandon': '放弃本局',
  'game.enterDigit': '填入 {{digit}}，还剩 {{count}} 个',
  'game.undo': '撤销',
  'game.erase': '擦除',
  'game.quick': '快速铅笔',
  'game.pencil': '铅笔',
  'game.hint': '提示',
  'game.active': '已开启',
  'game.remaining': '剩余 {{count}} 次',
  'hint.smart': '智能提示',
  'hint.stepProgress': '第 {{current}} / {{total}} 步',
  'hint.close': '关闭',
  'hint.back': '上一步',
  'hint.showResult': '查看结果',
  'hint.showResultAccessibility': '直接查看提示结论',
  'hint.applying': '正在应用…',
  'hint.applyStep': '应用这一步',
  'hint.next': '下一步',
  'result.complete': '完成题目',
  'result.ended': '本次尝试结束',
  'result.perfect': '完美完成——没有错误，也没有使用智能提示。',
  'result.saved': '进度和奖励已安全保存。',
  'result.failed': '可以重试当前题目，或选择其他难度。',
  'result.time': '用时',
  'result.mistakes': '错误',
  'result.hints': '提示',
  'result.firstReward': '首次完成奖励',
  'result.quickReward': '快速铅笔 +{{count}}',
  'result.hintReward': '智能提示 +{{count}}',
  'result.perfectBonus': '完美奖励',
  'result.streakBonus': '连续完成奖励',
  'result.nextPuzzle': '下一道 Level {{level}} 题目',
  'result.retry': '重试当前题目',
  'result.chooseLevel': '选择其他难度',
  'board.label': '数独棋盘',
  'board.cell': '第 {{row}} 行，第 {{column}} 列',
  'board.empty': '空格',
  'board.candidates': '候选数 {{digits}}',
  'board.incorrect': '错误数字',
  'board.hintRegion': '提示聚焦区域',
  'board.hintCell': '提示聚焦单元格',
  'board.valueEvidence': '作为提示依据的已填数字',
  'board.premise': '推理前提 {{digits}}',
  'board.remove': '删除候选数 {{digits}}',
  'board.ruledOut': '被排除的候选数 {{digits}}',
  'board.place': '填入 {{digit}}',
  'board.potential': '潜在模式单元格',
  'board.established': '已成立模式单元格',
  'board.affected': '受影响候选单元格',
  'board.result': '提示结果单元格',
  'message.game_not_active': '游戏当前未进行。',
  'message.game_not_paused': '游戏当前未暂停。',
  'message.hint_in_progress': '请先关闭或应用当前提示。',
  'message.no_selected_cell': '请先选择一个空格。',
  'message.given_cell': '题目给定的数字不能修改。',
  'message.filled_cell': '编辑候选数前请先擦除已填数字。',
  'message.nothing_to_erase': '这个单元格没有可擦除的内容。',
  'message.nothing_to_undo': '当前没有可以撤销的操作。',
  'message.quick_draft_missing': '请先生成快速候选。',
  'message.incorrect_values': '请先改正高亮显示的错误数字。',
  'message.conflicting_values': '请先解决相互冲突的数字。',
  'message.unsolvable_values': '当前盘面无法产生有效的逻辑步骤。',
  'message.insufficient_quick_pencil_credits': '快速铅笔额度已经用完。',
  'message.insufficient_smart_hint_credits': '智能提示额度已经用完。',
  'message.hint_already_active': '当前已经打开了一个提示。',
  'message.no_active_hint': '当前没有可以应用的提示。',
  'message.invalid_hint': '提示已经与当前盘面不匹配。',
  'message.action_failed': '无法完成这个操作。',
  'message.unexpected_error': '发生了意外错误。',
  'message.board_already_solved': '当前棋盘已经完成。',
  'message.invalid_hint_board': '当前盘面不能用于生成逻辑提示。',
  'message.no_supported_hint': '当前没有可用的受支持逻辑步骤。',
  'message.saved_catalog_changed': '保存的游戏属于旧版本题库。',
  'message.saved_puzzle_missing': '保存的题目已经不可用。',
  'message.level_unavailable': '当前没有 Level {{level}} 的题目。',
  'message.level_replay': '这个难度的题目已经全部完成，开始重复挑战。',
};

export const TRANSLATIONS: Readonly<
  Record<ProductLocale, TranslationResource>
> = {
  en: english,
  ja: japanese,
  de: german,
  'zh-Hans': simplifiedChinese,
};
